

#Gem Strength Powers
every 1 second:
	loop all players:
		loop all items in loop-player's inventory:
			if nbt compound of loop-item has tag "PublicBukkitValues;blissgems:gem-type":
				if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-item%" is "strength":
					if {_nomultiple::*} doesn't contain string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item:
						if isregisteredgem(string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item) is true:
							add string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item to {_nomultiple::*}
							#Chad

							if getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") > 0:
								#Remove 1
								setcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%", getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") - 1)

							#Enchanting

							if getcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") > 0:
								#Remove 1
								setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%", getcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") - 1)

							#Frailer

							if getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") > 0:
								#Remove 1
								setcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%", getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%") - 1)


							if {-Disabled.%uuid of loop-player%} is not set:
								set {-Disabled.%uuid of loop-player%} to 0


					


every 1 tick:
	loop all players:
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-player's held item%" is "strength":
			if isregisteredgem(string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item) is true:



			if getcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%") < 1:
				
			
				if line 3 of lore of loop-player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
					send "<##F10303>🔮 <##B8FFFB>Auto Enchanting" to loop-player
					
					

					if loop-player has a dragon egg:
						#5 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 300)
					
					else:
						#10 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 600)

					loop all items in loop-player's inventory:
						if loop-item is a sword:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 5

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 2

						else if loop-item is an axe:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 5

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 2
							
				else if lore of loop-player's held item contains "<##57FF8F>Scratched":
					if loop-player has a dragon egg:
						#5 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 300)
					
					else:
						#10 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 600)

					loop all items in loop-player's inventory:
						if loop-item is a sword:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 4

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 2

						else if loop-item is an axe:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 4

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 2


				else if lore of loop-player's held item contains "<##7958DB>Cracked":
					send "<##F10303>🔮 <##B8FFFB>Auto Enchanting" to loop-player
					if loop-player has a dragon egg:
						#5 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 375)
					
					else:
						#10 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 750)


					loop all items in loop-player's inventory:
						if loop-item is a sword:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 3

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 1

						else if loop-item is an axe:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 3

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 1

					
				else if lore of loop-player's held item contains "<##FFC929>Damaged":
					send "<##F10303>🔮 <##B8FFFB>Auto Enchanting" to loop-player
					if loop-player has a dragon egg:
						#5 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 450)
					
					else:
						#10 Minutes
						setcooldownvar("Enchanting:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%", 900)


					loop all items in loop-player's inventory:
						if loop-item is a sword:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 2

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 1

						else if loop-item is an axe:
							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
								enchant loop-item with sharpness 2

							if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
								enchant loop-item with sharpness 1



				




#V1 Code (Needs recode)
on damage:	
	set {_uuid} to uuid of attacker
	if {Disabled.%{_uuid}%} < 1:
		
		
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of attacker's off hand item%" is "strength":
			if "%int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of attacker's off hand item%" is "2":
				if attacker's health < 3:
					add 8 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage

			else if "%int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of attacker's off hand item%" is "1":
				if attacker's health < 2:
					add 6 to damage
				if attacker's health is 2.5:
					add 5.5 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage



on damage:
	if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of attacker's held item%" is "strength":
		if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of attacker's held item is 1:
			send "<##F10303>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to attacker
	set {_uuid} to uuid of attacker
	if {Disabled.%{_uuid}%} < 1:
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of attacker's held item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of attacker's held item is 2:
				
				
				if getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of attacker's held item%") < 1:
					loop {Bliss.Trusted.%{_uuid}%::*}:
						if loop-value is victim's uuid:
						
							send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to attacker
							set {_no} to true

					if {_no} is not true:

						send "<##F10303>🔮 <##B8FFFB>You have activated &f🤺<##F10303>Frailer <##B8FFFB>skill on <##F10303>%victim%" to attacker
						send "<##F10303>🔮 <##B8FFFB>You have been affected with &f🤺<##F10303>Frailer <##B8FFFB>by <##F10303>%attacker%" to victim
						#potion effects
						victim.clearActivePotionEffects()
							
						apply weakness to victim for 20 seconds

						if line 3 of lore of attacker's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
							set {_num} to 5
							set {_cooldown} to 240
						else if lore of attacker's held item contains "<##57FF8F>Scratched":
							set {_num} to 5
							set {_cooldown} to 289
						else if lore of attacker's held item contains "<##7958DB>Cracked":
							set {_num} to 4
							set {_cooldown} to 356
						else if lore of attacker's held item contains "<##FFC929>Damaged":
							set {_num} to 3
							set {_cooldown} to 384
						else if lore of attacker's held item contains "<##FF1111>Ruined":
							set {_num} to 2
							set {_cooldown} to 480
							
						if attacker has a dragon egg:
							set {_cooldown2} to {_cooldown} / 2
							setcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of attacker's held item%", {_cooldown2})

						else:
							setcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of attacker's held item%", {_cooldown})
						
						loop 400 times:
							if attacker is alive:
								set {_loc1} to the location 0.8 meters under attacker's head
							else:
								exit 1 loop
			
			
							if victim is alive:
								set {_loc2} to the location 0.8 meters under victim's head
							else:
								exit 1 loop
					
			
							set {_v} to vector from {_loc1} to {_loc2}
							set vector length of {_v} to 0.1
							
			
							loop (distance between {_loc1} and {_loc2}) / 0.1 times:
								draw 1 dust using dustOption(rgb(241, 3, 3), 1.1) at {_loc1} with extra 0 with force for {Bliss.Particles.Default::*}
								draw 1 of smoke at {_loc1} with extra 0 with force for {Bliss.Particles.Default::*}
								set {_loc1} to {_loc1} ~ {_v}
							wait 1 tick


			


				else:
					set {_secfr} to 0
					set {_minfr} to 0
					loop getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of attacker's held item%") times:
						
						add 1 to {_secfr}
						if {_secfr} is 60:
							add 1 to {_minfr}
							set {_secfr} to 0
					
	
					if {_secfr} is 0:
						if {_minfr} > 0:
							set {_fr} to "&b%{_minfr}%m"
		
	
					else if {_minfr} > 0:
						set {_fr} to "&b%{_minfr}%m %{_secfr}%s"					
	
					else:
						set {_fr} to "&b%{_secfr}%s"
	
					if {_secfr} is 0:
						if {_minfr} is 0:
							set {_fr} to "&aReady!"
	
	
					
					replace all "&b" with "" in {_fr}
					send "<##F10303>🔮 <##FD8988>Your &f🤺<##F10303>Frailer <##FD8988>skill is on cooldown for <##F10303>%{_fr}%" to attacker



		



on left click:
	if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item%" is "strength":
		if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 1:
			send "<##F10303>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 2:
					
				if getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") is 0:

					if line 3 of lore of player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
						set {_num} to 5
						set {_cooldown} to 240
					else if lore of player's held item contains "<##57FF8F>Scratched":
						set {_num} to 5
						set {_cooldown} to 289
					else if lore of player's held item contains "<##7958DB>Cracked":
						set {_num} to 4
						set {_cooldown} to 356
					else if lore of player's held item contains "<##FFC929>Damaged":
						set {_num} to 3
						set {_cooldown} to 384
					else if lore of player's held item contains "<##FF1111>Ruined":
						set {_num} to 2
						set {_cooldown} to 480
						
					if player has a dragon egg:
						set {_cooldown2} to {_cooldown} / 2
						setcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%", {_cooldown2})

					else:
						setcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%", {_cooldown})
						
					send "<##F10303>🔮 <##B8FFFB>You have activated group &f🤺<##F10303>Frailer <##B8FFFB>skill &7(radius 5)" to player

					set {_s} to 0.5
					loop {_num} + {_num} times:

						if loop-value is not {_num} + {_num}:

							if {_s} is not 0.5:
								StrengthCircle({_s}, player)
					
							add 0.5 to {_s}

						else:
							StrengthCirclelast({_s}, player)


					
					set {_strengthholder} to player
					loop all entities within {_num} blocks of the player:
						if loop-entity is not player:
							if "%{Bliss.Trusted.%{_uuid}%::*}%" does not contain "%loop-entity's uuid%":
								remove all potions from loop-entity
								apply potion of wither of tier 1 to loop-entity for 20 seconds
								send "<##F10303>🔮 <##B8FFFB>You have been affected with &f🤺<##F10303>Frailer <##B8FFFB>by <##F10303>%{_strengthholder}%" to loop-entity


							else:
								send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to {_strengthholder}
				else:
					set {_secfr} to 0
					set {_minfr} to 0
					loop getcooldownvar("Frailer:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") times:
						
						add 1 to {_secfr}
						if {_secfr} is 60:
							add 1 to {_minfr}
							set {_secfr} to 0
					
	
					if {_secfr} is 0:
						if {_minfr} > 0:
							set {_fr} to "&b%{_minfr}%m"
		
	
					else if {_minfr} > 0:
						set {_fr} to "&b%{_minfr}%m %{_secfr}%s"					
	
					else:
						set {_fr} to "&b%{_secfr}%s"
	
					if {_secfr} is 0:
						if {_minfr} is 0:
							set {_fr} to "&aReady!"
	
	
					
					replace all "&b" with "" in {_fr}
					send "<##F10303>🔮 <##FD8988>Your &f🤺<##F10303>Frailer <##FD8988>skill is on cooldown for <##F10303>%{_fr}%" to player




		


				





on right click:
	if target entity is not player:
		if target entity is set:
			if distance between player and target entity < 3:
				set {_uuid} to uuid of player 
				if {Disabled.%{_uuid}%} < 1:
					if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item%" is "strength":
						if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 2:
							set {_uuid} to uuid of player



							if getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") is 0:
								send "<##F10303>🔮 %player% <##B2FFF6>gave you &f⚔<##F10303>Chad Strength <##B2FFF6>for <##F10303>40 seconds" to player


								loop all players within 2 blocks of target entity:
									if loop-entity is not player:
										if "%{Bliss.Trusted.%{_uuid}%::*}%" contains "%loop-player's uuid%":
											send "<##F10303>🔮 %player% <##B2FFF6>gave you &f⚔<##F10303>Chad Strength <##B2FFF6>for <##F10303>40 seconds" to loop-player
											set {-Bliss.Damages.Strength.Attacker.%uuid of loop-player%.Group} to 0
											set {-Bliss.Damages.Strength.Attacker.%uuid of loop-player%.Group.Activated} to true
											set {-Bliss.Damages.Strength.Attacker.%uuid of loop-player%.Group.Timer} to 40
											set {-ChadStrength.Particles.%uuid of loop-player%.single} to 1
					

								send "<##F10303>🔮 <##B2FFF6>You used group &f⚔<##F10303>Chad Strength &7(radius 2)" to player
								
								StrengthCircleChad(1, target entity)	
								StrengthCircleChad(1.5, target entity)
								StrengthCircleChad(2, target entity)	
								StrengthCircleChad(2.5, target entity)	
								StrengthCircleChad(3, target entity)	
								StrengthCircleChad(3.5, target entity)	
								StrengthCircleChadLast(4, target entity)





									
								set {-Bliss.Damages.Strength.Attacker.%uuid of player%.Group} to 0
								set {-Bliss.Damages.Strength.Attacker.%uuid of player%.Group.Activated} to true
								set {-Bliss.Damages.Strength.Attacker.%uuid of player%.Group.Timer} to 40

								if line 3 of lore of player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
									set {_num} to 5
									set {_cooldown} to 150
								else if lore of player's held item contains "<##57FF8F>Scratched":
									set {_num} to 5
									set {_cooldown} to 180
								else if lore of player's held item contains "<##7958DB>Cracked":
									set {_num} to 4
									set {_cooldown} to 210
								else if lore of player's held item contains "<##FFC929>Damaged":
									set {_num} to 3
									set {_cooldown} to 250
								else if lore of player's held item contains "<##FF1111>Ruined":
									set {_num} to 2
									set {_cooldown} to 300
						


								if player has a dragon egg:
									set {_cooldown2} to {_cooldown} / 2
									setcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%", {_cooldown2})
							
								else:
									setcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%", {_cooldown})

								wait 3 ticks
								set {-singlechad %{_uuid}%} to false

								set {-ChadStrength.Particles.%{_uuid}%.single} to 1
								wait 40 seconds
								set {-ChadStrength.Particles.%{_uuid}%.single} to 0



							else:
								set {_secch} to 0
								set {_minch} to 0
								loop getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") times:
									
									add 1 to {_secch}
									if {_secch} is 60:
										add 1 to {_minch}
										set {_secch} to 0
								
				
								if {_secch} is 0:
									if {_minch} > 0:
										set {_ch} to "&b%{_minch}%m"
					
				
								else if {_minch} > 0:
									set {_ch} to "&b%{_minch}%m %{_secch}%s"					
				
								else:
									set {_ch} to "&b%{_secch}%s"
				
								if {_secch} is 0:
									if {_minch} is 0:
										set {_ch} to "&aReady!"
				
				
								
								replace all "&b" with "" in {_ch}
								send "<##F10303>🔮 <##FD8988>Your &f⚔<##F10303>Chad Strength <##FD8988>skill is on cooldown for <##F10303>%{_ch}%" to player
		

function chadstrengthsingle(p: player):
	draw 20 of dust using dustOption(rgb(241, 3, 3), 1) at location 1 block above {_p} with offset vector(0.5, 1, 0.5) with extra 0

	draw 20 of smoke at location 1 block above {_p} with offset vector(0.5, 1, 0.5) with extra 0

	draw 20 of happy villager at location 1 block above {_p} with offset vector(0.5, 1, 0.5) with extra 0

	send "<##F10303>🔮 <##B8FFFB>You activated &f⚔<##F10303>Chad Strength" to {_p}
	set {-ChadStrength..%{_p}%.particle} to true
	set {-Bliss.Damages.Strength.Attacker.%uuid of {_p}%.Group} to 0
	if line 3 of lore of {_p}'s held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
		set {_num} to 5
		set {_cooldown} to 150
	else if lore of {_p}'s held item contains "<##57FF8F>Scratched":
		set {_num} to 5
		set {_cooldown} to 180
	else if lore of {_p}'s held item contains "<##7958DB>Cracked":
		set {_num} to 4
		set {_cooldown} to 210
	else if lore of {_p}'s held item contains "<##FFC929>Damaged":
		set {_num} to 3
		set {_cooldown} to 250
	else if lore of {_p}'s held item contains "<##FF1111>Ruined":
		set {_num} to 2
		set {_cooldown} to 300



	if {_p} has a dragon egg:
		set {_cooldown2} to {_cooldown} / 2
		setcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of {_p}'s held item%", {_cooldown2})

	else:
		setcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of {_p}'s held item%", {_cooldown})

	
	
	set {-ChadStrength..%uuid of {_p}%.particle} to true
	set {-Bliss.Damages.Strength.Attacker.%uuid of {_p}%.Single} to 0
	set {-Strength.Power3.Chad.Activated.Single.%uuid of {_p}%} to true
	set {-ChadStrength.Particles.%uuid of {_p}%} to 1
	wait 40 seconds
	set {-ChadStrength.Particles.%uuid of {_p}%} to 0
	set {-Strength.Power3.Chad.Activated.Single.%uuid of {_p}%} to false
	set {-Bliss.Damages.Strength.Attacker.%uuid of {_p}%.Single} to 0
	set {-ChadStrength..%uuid of {_p}%.particle} to false

on right click:
	if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item%" is "strength":
		if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 1:
			send "<##F10303>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player
	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 2:
				if getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") is 0:
					if distance between player and target entity > 3:
						chadstrengthsingle(player)

					else if target entity is not set:
						chadstrengthsingle(player)
				else:
					set {_secch} to 0
					set {_minch} to 0
					loop getcooldownvar("Chad:%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%") times:
						
						add 1 to {_secch}
						if {_secch} is 60:
							add 1 to {_minch}
							set {_secch} to 0
					
	
					if {_secch} is 0:
						if {_minch} > 0:
							set {_ch} to "&b%{_minch}%m"
		
	
					else if {_minch} > 0:
						set {_ch} to "&b%{_minch}%m %{_secch}%s"					
	
					else:
						set {_ch} to "&b%{_secch}%s"
	
					if {_secch} is 0:
						if {_minch} is 0:
							set {_ch} to "&aReady!"
	
	
					
					replace all "&b" with "" in {_ch}
					send "<##F10303>🔮 <##FD8988>Your &f⚔<##F10303>Chad Strength <##FD8988>skill is on cooldown for <##F10303>%{_ch}%" to player


					
#every 1 tick:
#	loop all players:
#		loop all entities:
#			if {-StrengthLine.%loop-player-1's uuid%.%loop-entity-2's uuid%} is true:
#				set {_v} to vector from loop-player-1's head to loop-entity-2's head
#				set vector length of {_v} to 0.5
#				set {_loc1} to the location 0.8 meters under loop-player-1's head
#				set {_loc2} to the location 0.8 meters under loop-entity-2's head
#				loop (distance between {_loc1} and {_loc2}) / 0.5 times:
#
#					draw 1 dust using dustOption(rgb(241, 3, 3), 1.1) at {_loc1} with force for {Bliss.Particles.Less::*}
#					draw 1 of smoke at {_loc1} with extra 0 with force for {Bliss.Particles.Less::*}
#					set {_loc1} to {_loc1} ~ {_v}



	


function StrengthCircleChad(s: number, p: entity):
	set {_pl} to location of {_p}
	
	loop 360 times:
		set {_v} to spherical vector with radius {_s}, yaw loop-value and pitch 0
		make 1 of dust using dustOption(rgb(241, 3, 3), 0.9) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
		draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}

function StrengthCircleChadLast(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 10 times:
		loop 360 times:
			set {_v} to spherical vector with radius {_s}, yaw loop-value-2 and pitch 0
			make 1 of dust using dustOption(rgb(241, 3, 3), 0.9) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
			draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
		wait 0.3 seconds


function StrengthCircle(s: number, p: entity):
	StrengthCircleLess({_s}, {_p})	   
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 1.5
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(rgb(241, 3, 3), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}

		
		

function StrengthCircleLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 3  # Adjust the angle increment
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
		make 1 of dust using dustOption(rgb(241, 3, 3), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}


function StrengthCirclelast(s: number, p: entity):
	StrengthCirclelastLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 1.5
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
			make 1 of dust using dustOption(rgb(241, 3, 3), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}
		wait 0.3 seconds


function StrengthCirclelastLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 3  # Adjust the angle increment
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
			make 1 of dust using dustOption(rgb(241, 3, 3), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}
		wait 0.3 seconds



every 1 second:
	loop all players:
		if {-singlefrailer %{_uuid}%} is not set:
			set {_uuid} to uuid of loop-player
			set {-singlefrailer %{_uuid}%} to false

		if {-singlechad %{_uuid}%} is not set:
			set {_uuid} to uuid of loop-player
			set {-singlechad %{_uuid}%} to false

every 1 tick:
	loop all players:
		if {-ChadStrength..%uuid of loop-player%.particle} is true:
			#draw 5 of dust using dustOption(dark red, 1) at loop-player
			set {_pl1} to location 0.5 metres infront and 1.1 metres above loop-player
			set {_pl2} to location 0.3 metres infront and 1.1 metres above and 0.4 metres left of and 0.1 metres behind loop-player
			set {_pl3} to location 0.3 metres infront and 1.1 metres above and 0.4 metres right of and 0.1 metres behind loop-player

			#draw 1 of smoke at {_pl2} with extra 0 with force


			if {-ChadStrength.Particles.%uuid of loop-player%} is 1:
				draw 1 smoke at {_pl1} with extra 0 with force
				draw 1 smoke at {_pl2} with extra 0 with force
				draw 1 smoke at {_pl3} with extra 0 with force

			if {-ChadStrength.Particles.%uuid of loop-player%} is 2:
				draw 1 smoke at {_pl1} with extra 0 with force
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl2} with extra 0 with force
				draw 1 smoke at {_pl3} with extra 0 with force

			if {-ChadStrength.Particles.%uuid of loop-player%} is 3:
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl1} with extra 0 with force
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl2} with extra 0 with force
				draw 1 smoke at {_pl3} with extra 0 with force


			if {-ChadStrength.Particles.%uuid of loop-player%} is 4:
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl1} with extra 0 with force
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl2} with extra 0 with force
				draw 1 dust using dustOption(rgb(241, 3, 3), 1) at {_pl3} with extra 0 with force




every 1 second:
	loop all players:
		if {-singlefrailer %{_uuid}%} is not set:
			set {_uuid} to uuid of loop-player
			set {-singlefrailer %{_uuid}%} to false

		if {-singlechad %{_uuid}%} is not set:
			set {_uuid} to uuid of loop-player
			set {-singlechad %{_uuid}%} to false


					
on damage:
	set {_uuid} to uuid of attacker
	if "%{Bliss.Trusted.%{_uuid}%::*}%" does not contain "%victim's uuid%":
		if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group} < 8:
			if fall distance of attacker is less than 0.7:
				if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group.Activated} is true:
					add 1 to {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group}

					if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group} is 8:
						set {-ChadStrength.Particles.%{_uuid}%.single} to 2

						

		

		else:
			if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group.Activated} is true:
				if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group} is 8:
					if fall distance of attacker is less than 0.7:
						add damage to damage
						set {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Group} to 0
						set {-ChadStrength.Particles.%{_uuid}%.single} to 1

							
every 1 second:
	loop all offlineplayers:
		if {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group.Activated} is true:
			if {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group.Timer} > 0:

				remove 1 from {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group.Timer}

				if {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group.Timer} is 0:

					set {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group.Activated} to false
					set {-Bliss.Damages.Strength.Attacker.%uuid of loop-offlineplayer%.Group} to 0
					set {-ChadStrength.Particles.%uuid of loop-offlineplayer%.single} to 0

					
every 1 tick:
	loop all players:
		if {-ChadStrength.Particles.%uuid of loop-player%.single} is 1:
			draw 1 smoke at location 2.5 blocks above loop-player with extra 0 with force

		else if {-ChadStrength.Particles.%uuid of loop-player%.single} is 2:
			draw 1 dust using dustOption(rgb(241, 3, 3), 1) at location 2.5 blocks above loop-player

on damage:
	if {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Single} < 3:
		if {-Strength.Power3.Chad.Activated.Single.%uuid of attacker%} is true:
			if fall distance of attacker is less than 0.7:
				add 1 to {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Single}
				add 1 to {-ChadStrength.Particles.%uuid of attacker%}

	

	else:
		if {-Strength.Power3.Chad.Activated.Single.%uuid of attacker%} is true:
			if fall distance of attacker is less than 0.7:
				add damage to damage
				set {-Bliss.Damages.Strength.Attacker.%uuid of attacker%.Single} to 0
				set {-ChadStrength.Particles.%uuid of attacker%} to 1





				
on join:
	set {_uuid} to uuid of player
	set {-singlefrailer %{_uuid}%} to false
	set {-singlechad %{_uuid}%} to false


			

every 0.2 second:
	loop all players:
		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-player's off hand item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's off hand item is 1:
				apply strength 1 without particles to loop-player for 2 seconds replacing the existing effect

		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-player's held item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 1:
				apply strength 1 without particles to loop-player for 2 seconds replacing the existing effect

		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-player's held item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's held item is 2:
				apply strength 2 without particles to loop-player for 2 seconds replacing the existing effect


		if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-player's off hand item%" is "strength":
			if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-player's off hand item is 2:
				apply strength 2 without particles to loop-player for 2 seconds replacing the existing effect







