#ᴀsᴛʀᴀ ɢᴇᴍ




every 1 second:
	loop all players:
		loop all items in loop-player's inventory:
			if nbt compound of loop-item has tag "PublicBukkitValues;blissgems:gem-type":
				if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-item%" is "astra":
					if {_nomultiple::*} doesn't contain string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item:
						add string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item to {_nomultiple::*}
						#Projection

						if {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power3.Projection.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power3.Projection.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false

					
						if {-Astra.Power3.Projection.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}

						
						if {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							remove 1 from {-Astra.Power3.Projection.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
							set {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59
							

						if {-Astra.Power3.Projection.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Astra.Power3.Projection.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
							set {-Astra.Power3.Projection.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power3.Projection.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0







						#entity stored in ur gem

						if {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false



						if {-Astra.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}



							if {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
								remove 1 from {-Astra.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
								set {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59

								if {-Astra.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
									set {-Astra.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
									set {-Astra.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
									set {-Astra.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0





						

							
							
						if {-Astra.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Astra.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false






							

						#Daggers





						if {-Astra.Power1.Daggers.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}


						if {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power1.Daggers.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power1.Daggers.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
						
						if {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							remove 1 from {-Astra.Power1.Daggers.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
							set {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59

						

						if {-Astra.Power1.Daggers.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Astra.Power1.Daggers.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
							set {-Astra.Power1.Daggers.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Astra.Power1.Daggers.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0




						if {-Disabled.%uuid of loop-player%} is not set:
							set {-Disabled.%uuid of loop-player%} to 0


						




on npc left click:
	loop all players:
		set {_uuid} to uuid of loop-player

		if npc is {-AstralNPC.%{_uuid}%.ID}:
			set {_c} to "%loop-player's name%" parsed as offline player
			set {_cuuid} to uuid of {_c}

			set {-Astra.Power3.Projection.Activated.%{_uuid}%} to false
			if loop-player's gamemode is not creative:
				set fly mode of loop-player to false
			teleport loop-player to {-Astra.Power3.Projection.Location.%{_uuid}%}
			set loop-player's gamemode to survival
			set {_slot} to 0
			clear loop-player's inventory
			set {_slot} to 0
			loop 41 times:
				set slot {_slot} of loop-player's inventory to {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_slot}%}
				add 1 to {_slot}
				
			

			destroy citizen {-AstralNPC.%{_uuid}%.ID}
			remove invisibility from loop-player
			execute console command "effect clear %loop-player% minecraft:invisibility"


			if {Bliss.GemHealth.%{_uuid}%} > 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} is 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} < 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
		

			



every 1 tick:
	loop all players:
		if {-Astra.Power3.Projection.Activated.%uuid of loop-player%} is true:
			if the distance between location of loop-player and {-Astra.Power3.Projection.Location.%uuid of loop-player%} > 150:
				push loop-player (direction from loop-player to {-Astra.Power3.Projection.Location.%uuid of loop-player%}) at speed 1



			

every 1 tick:
	loop all players:
		loop {-Nofallentities.%uuid of loop-player%::*}:


			teleport citizen loop-value-2 to {-Nofallentities.%uuid of loop-player%::%loop-value-2%.Location}
			
	

on disconnect:
	set {_uuid} to uuid of player
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		set {-Astra.Power3.Projection.Activated.%{_uuid}%} to false
		teleport player to {-Astra.Power3.Projection.Location.%{_uuid}%}

		set {_slot} to 0
		clear player's inventory
		
		set {_slot} to 0
		loop 41 times:
			set slot {_slot} of player's inventory to {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_slot}%}
			add 1 to {_slot}
			

			
		
		set player's gamemode to survival
		destroy citizen {-AstralNPC.%{_uuid}%.ID}
		kill {-AstralNPC.%{_uuid}%}
		remove invisibility from player
		execute console command "effect clear %player% minecraft:invisibility"

		if {Bliss.GemHealth.%{_uuid}%} > 3:
			set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
			set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
			set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
		if {Bliss.GemHealth.%{_uuid}%} is 3:
			set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
			set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
			set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
		if {Bliss.GemHealth.%{_uuid}%} < 3:
			set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
			set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
			set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true


				




on server stop:
	loop all players:
		set {_uuid} to uuid of loop-player
		if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
			set {-Astra.Power3.Projection.Activated.%{_uuid}%} to false
			teleport loop-player to {-Astra.Power3.Projection.Location.%{_uuid}%}
	
			set loop-player's gamemode to survival
			clear loop-player's inventory
			set {_slot} to 0
			loop 41 times:
				set slot {_slot} of loop-player's inventory to {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_slot}%}
				add 1 to {_slot}
				
			if {Bliss.GemHealth.%{_uuid}%} > 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} is 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} < 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true	
			
	
			destroy citizen {-AstralNPC.%{_uuid}%.ID}
			kill {-AstralNPC.%{_uuid}%}
			remove invisibility from loop-player
			execute console command "effect clear %loop-player% minecraft:invisibility"
	
	



on damage:
	loop all players:
		set {_uuid} to uuid of loop-player

		if victim is {-AstralNPC.%{_uuid}%}:
			cancel event
			
			
			set loop-player's gamemode to survival
			set {-Astra.Power3.Projection.Activated.%{_uuid}%} to false
			if loop-player's gamemode is not creative:
				set fly mode of loop-player to false
			teleport loop-player to {-Astra.Power3.Projection.Location.%{_uuid}%}
			

			clear loop-player's inventory
			set {_slot} to 0
			loop 41 times:
				set slot {_slot} of loop-player's inventory to {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_slot}%}
				add 1 to {_slot}
				
				
			if {Bliss.GemHealth.%{_uuid}%} > 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} is 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} < 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true

			kill {-AstralNPC.%{_uuid}%}
			remove invisibility from loop-player
			execute console command "effect clear %loop-player% minecraft:invisibility"
		

on damage:
	set {_uuid} to uuid of victim
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		cancel event

on damage:
	set {_uuid} to uuid of attacker
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		cancel event

on death:
	set {_uuid} to uuid of victim
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		cancel event
		

command held:
	trigger:
		broadcast name of player's held item



on right click:
	if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of player's held item is "astra":
		if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 2:
			if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
				if player is not sneaking:
					set {_uuid} to uuid of player
					if {Disabled.%{_uuid}%} < 1:
						#if {-Astra.Power3.Projection.Activated.%{_uuid}%} is not true:
							#if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is not true:
						if {Daggers.on.%{_uuid}%} is not true:
							
							set {_uuid} to uuid of player 


							set {-Astra.Power3.Projection.Location.%{_uuid}%} to location of player
							send "<##A01FFF>🔮 <##B8FFFB>You have activated <##AABBBF>Astral Projection"

							set {-Astra.Power3.Projection.Activated.%{_uuid}%} to true

							remove player from bossbar players of {Dagger.Bar.%{_uuid}%}
							set {Daggers.1.%{_uuid}%.shotdagger} to true
							set {Daggers.2.%{_uuid}%.shotdagger} to true
							set {Daggers.3.%{_uuid}%.shotdagger} to true
							set {Daggers.4.%{_uuid}%.shotdagger} to true
							set {Daggers.5.%{_uuid}%.shotdagger} to true
							set {Shootdagger.%{_uuid}%} to 0
				
							set {Daggers.on.%{_uuid}%} to false
				
							if {Daggers.5.%{_uuid}%} is not {Daggers.5.%{_uuid}%.real}:
								kill {Daggers.5.%{_uuid}%}
				
							if {Daggers.4.%{_uuid}%} is not {Daggers.4.%{_uuid}%.real}:
								kill {Daggers.4.%{_uuid}%}
				
							if {Daggers.3.%{_uuid}%} is not {Daggers.3.%{_uuid}%.real}:
								kill {Daggers.3.%{_uuid}%}
				
							if {Daggers.2.%{_uuid}%} is not {Daggers.2.%{_uuid}%.real}:
								kill {Daggers.2.%{_uuid}%}
				
							if {Daggers.1.%{_uuid}%} is not {Daggers.1.%{_uuid}%.real}:
								kill {Daggers.1.%{_uuid}%}
				

							set {_s} to 0
							loop 41 times:
								clear {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_s}%}
								add 1 to {_s}

							clear {-Astra.Power3.Projection.Inventory.%{_uuid}%::*}

							loop all items in player's inventory:
								set {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%index of loop-item%} to loop-item
							

						
							set {_i} to player's held item

							set player's gamemode to spectator
							
							
							apply invisibility without particles to player for 9999999999999999999 seconds
							set fly mode of player to true
							if plugin "Citizens" is enabled:

								create citizen named "%player%" at player
								set {-AstralNPC.%{_uuid}%.ID} to last created citizen id
								
								change citizen {-AstralNPC.%{_uuid}%.ID} skin to "%player%"
								set {-AstralNPC.%{_uuid}%} to last created citizen

								add {-AstralNPC.%{_uuid}%.ID} to {-Nofallentities.%uuid of player%::*}
								set {-Nofallentities.%uuid of player%::%{-AstralNPC.%{_uuid}%.ID}%.Location} to location of player
								
								
								make citizen {-AstralNPC.%{_uuid}%.ID} hold player's held item
								#make citizen {-AstralNPC.%{_uuid}%.ID} vulnerable

								equip citizen {-AstralNPC.%{_uuid}%.ID} with player's chestplate
								equip citizen {-AstralNPC.%{_uuid}%.ID} with player's leggings
								equip citizen {-AstralNPC.%{_uuid}%.ID} with player's boots
								equip citizen {-AstralNPC.%{_uuid}%.ID} with player's helmet
								
								set citizen {-AstralNPC.%{_uuid}%.ID}'s offhand to player's offhand
								

								
								clear player's inventory
								set player's held item to {_i}
						

							else:


								spawn zombified piglin at player
								set {-AstralNPC.%{_uuid}%} to last spawned entity
								set {-AstralNPC.%{_uuid}%.NBT} to nbt compound of {-AstralNPC.%{_uuid}%}
								add nbt compound of "{NoAI:1}" to {-AstralNPC.%{_uuid}%.NBT}
							
								set {-AstralNPC.%{_uuid}%}'s name to "%player%"
								add {-AstralNPC.%{_uuid}%.ID} to {-Nofallentities.%uuid of player%::*}
								set {-Nofallentities.%uuid of player%::%{-AstralNPC.%{_uuid}%.ID}%.Location} to location of player


								
								clear player's inventory
								set player's held item to {_i}


							while {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
								draw 20 of dust using dustOption(rgb(160, 31, 255), 1) at location 1 block above player with offset vector(0.3, 0.4, 0.3) with extra 0 with force
								wait 3 seconds
								


		else if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of player's held item is 1:
			if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
				if player is not sneaking:
					send "<##A01FFF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

on break:
	set {_uuid} to uuid of player
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		cancel event

on pick up:
	set {_uuid} to uuid of player
	if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
		cancel event


every 1 tick:
	loop all players:
		if {-Astra.Power3.Projection.Activated.%uuid of loop-player%} is true:
		

			if loop-player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
				if "%{entity.%uuid of loop-player%::*}%" is not "<none>":
					send action bar "&f🧊 &bSPOOK  <##A01FFF>🔮 %{entity.%uuid of loop-player%::*}%  &f🌟&bTAG" to loop-player
				else:
					send action bar "&f🧊 &bSPOOK  <##A01FFF>🔮  &f🌟&bTAG" to loop-player


			if loop-player's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
				if "%{entity.%uuid of loop-player%::*}%" is not "<none>":
					send action bar "&f🧊 &bSPOOK  <##A01FFF>🔮 %{entity.%uuid of loop-player%::*}%  &f🌟&bTAG" to loop-player
				else:
					send action bar "&f🧊 &bSPOOK  <##A01FFF>🔮  &f🌟&bTAG" to loop-player


on inventory click:
	if {-Astra.Power3.Projection.Activated.%uuid of player%} is true:
		if event-item is not a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
			if event-item is not air:
				if event-item is not player head named "<##E9C2FF>&lᴛʀᴀᴅᴇʀ":
					cancel event

on damage:
	wait 1 tick
	if attacker's held item is prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		set {_uuid} to uuid of attacker
		if {-Astra.Power3.Projection.Activated.%{_uuid}%} is true:
			send "<##A01FFF>🔮 <##B8FFFB>Spooked <##FEFD17>%victim% <##B8FFFB>for <##FEFD17>10 &7seconds" to attacker
			send "<##A01FFF>🔮 <##B8FFFB>You have been Spooked by <##FEFD17>%attacker% <##B8FFFB>for <##FEFD17>10 &7seconds" to victim

			apply blindness to victim for 10 seconds
			set {_uuidv} to uuid of victim
			add 10 to {Disabled.%{_uuidv}%}

			set {_uuid} to uuid of attacker
			set {-Astra.Power3.Projection.Activated.%{_uuid}%} to false
			if attacker's gamemode is not creative:
				set fly mode of attacker to false
			teleport attacker to {-Astra.Power3.Projection.Location.%{_uuid}%}

			if {Bliss.GemHealth.%{_uuid}%} > 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} is 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true
			if {Bliss.GemHealth.%{_uuid}%} < 3:
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 1
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true

			

			clear attacker's inventory
			set {_slot} to 0
			loop 41 times:
				set slot {_slot} of attacker's inventory to {-Astra.Power3.Projection.Inventory.%{_uuid}%.Indexes.%{_slot}%}
				add 1 to {_slot}

			destroy citizen {-AstralNPC.%{_uuid}%.ID}
			kill {-AstralNPC.%{_uuid}%}
			remove invisibility from attacker


function shootdagger5(p: player):
	set {_uuid} to uuid of {_p}

	wait 1 tick
	set {_loc} to location 0.25 metres above {_p}
	spawn armor stand at location of {_loc} with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%{_p}%dag5"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
	set {Daggers.5.%{_uuid}%} to last spawned entity
	set {Daggers.5.%{_uuid}%.real} to last spawned entity
	enchant {Daggers.5.%{_uuid}%.real}'s helmet with mending

	set {_pl} to location of {_p}
	set {_s} to 1
	while {Daggers.5.%{_uuid}%} is alive:
		if {Daggers.5.%{_uuid}%.shotdagger} is true:
			set {_loc5} to location {_s} metres infront and 0.50 metres above {_pl}
			add 1 to {_s}
			teleport {Daggers.5.%{_uuid}%} to {_loc5}
			set {_loc52} to location 1 block above and 3 metres behind {Daggers.5.%{_uuid}%}
			draw 1 dust using dustOption(rgb(160, 31, 255), 1) at {_loc52} with extra 0 with force

		wait 0.025 seconds



function shootdagger4(p: player):
	set {_uuid} to uuid of {_p}

	wait 1 tick
	set {_loc} to location 0.25 metres above {_p}
	spawn armor stand at location of {_loc} with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%{_p}%dag4"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
	set {Daggers.4.%{_uuid}%} to last spawned entity
	set {Daggers.4.%{_uuid}%.real} to last spawned entity
	enchant {Daggers.4.%{_uuid}%.real}'s helmet with mending

	set {_pl} to location of {_p}
	set {_s} to 1
	while {Daggers.4.%{_uuid}%} is alive:
		if {Daggers.4.%{_uuid}%.shotdagger} is true:
			set {_loc4} to location {_s} metres infront and 0.50 metres above {_pl}
			add 1 to {_s}
			teleport {Daggers.4.%{_uuid}%} to {_loc4}
			set {_loc42} to location 1 block above and 3 metres behind {Daggers.4.%{_uuid}%}
			draw 1 dust using dustOption(rgb(160, 31, 255), 1) at {_loc42} with extra 0 with force
		wait 0.025 seconds
		
			


function shootdagger3(p: player):
	set {_uuid} to uuid of {_p}

	wait 1 tick
	set {_loc} to location 0.25 metres above {_p}
	spawn armor stand at location of {_loc} with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%{_p}%dag3"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
	set {Daggers.3.%{_uuid}%} to last spawned entity
	set {Daggers.3.%{_uuid}%.real} to last spawned entity
	enchant {Daggers.3.%{_uuid}%.real}'s helmet with mending

	set {_pl} to location of {_p}
	set {_s} to 1
	while {Daggers.3.%{_uuid}%} is alive:
		
		if {Daggers.3.%{_uuid}%.shotdagger} is true:
			set {_loc3} to location {_s} metres infront and 0.50 metres above {_pl}
			add 1 to {_s}
			teleport {Daggers.3.%{_uuid}%} to {_loc3}
			set {_loc32} to location 1 block above and 3 metres behind {Daggers.3.%{_uuid}%}
			draw 1 dust using dustOption(rgb(160, 31, 255), 1) at {_loc32} with extra 0 with force

		wait 0.025 seconds




function shootdagger2(p: player):
	set {_uuid} to uuid of {_p}

	wait 1 tick
	set {_loc} to location 0.25 metres above {_p}
	spawn armor stand at location of {_loc} with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%{_p}%dag2"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
	set {Daggers.2.%{_uuid}%} to last spawned entity
	set {Daggers.2.%{_uuid}%.real} to last spawned entity
	enchant {Daggers.2.%{_uuid}%.real}'s helmet with mending

	set {_pl} to location of {_p}
	set {_s} to 1
	while {Daggers.2.%{_uuid}%} is alive:
		
		if {Daggers.2.%{_uuid}%.shotdagger} is true:
			set {_loc2} to location {_s} metres infront and 0.50 metres above {_pl}
			add 1 to {_s}
			teleport {Daggers.2.%{_uuid}%} to {_loc2}
			set {_loc22} to location 1 block above and 3 metres behind {Daggers.2.%{_uuid}%}
			draw 1 dust using dustOption(rgb(160, 31, 255), 1) at {_loc22} with extra 0 with force
		wait 0.025 seconds



function shootdagger1(p: player):
	set {_uuid} to uuid of {_p}
	
	wait 1 tick
	set {_loc} to location 0.25 metres above {_p}
	spawn armor stand at location of {_loc} with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%{_p}%dag"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
	set {Daggers.1.%{_uuid}%} to last spawned entity
	set {Daggers.1.%{_uuid}%.real} to last spawned entity
	enchant {Daggers.1.%{_uuid}%.real}'s helmet with mending

	
	set {_pl} to location of {_p}
	set {_s} to 1
	while {Daggers.1.%{_uuid}%} is alive:
		
		if {Daggers.1.%{_uuid}%.shotdagger} is true:
			set {_loc1} to location {_s} metres infront and 0.50 metres above {_pl}
			add 1 to {_s}
			teleport {Daggers.1.%{_uuid}%} to {_loc1}

			set {_loc12} to location 1 block above and 3 metres behind {Daggers.1.%{_uuid}%}

			draw 1 dust using dustOption(rgb(160, 31, 255), 1) at {_loc12} with extra 0 with force
		wait 0.025 seconds




every 0.1 seconds:
	loop all players:

		#if {AstraProjection.%loop-player%} is true:
		#	chance of 70%
		#	execute console command "execute as @e[tag=astrapart] at @s run particle dust 0.52 0.11 0.67 1 ~ ~1.2 ~ 0.1 0.1 0.1 1 1 normal"

		if {Shootdagger.%uuid of loop-player%} is 5:
			#teleport {Daggers.Location.%uuid of loop-player%} to loop-player

			teleport {Daggers.1.%uuid of loop-player%} to location 1.5 blocks infront and 0.1 metres right and 0.6 metres above loop-player
			teleport {Daggers.2.%uuid of loop-player%} to location 1.3 blocks infront and 0.8 metres left and 0.6 metres above loop-player
			teleport {Daggers.3.%uuid of loop-player%} to location 1.3 blocks infront and 1 metres right and 0.6 metres above loop-player
			teleport {Daggers.4.%uuid of loop-player%} to location 0.35 blocks infront and 1.1 metres left and 0.6 metres above loop-player
			teleport {Daggers.5.%uuid of loop-player%} to location 0.35 blocks infront and 1.2 metres right and 0.6 metres above loop-player

		else if {Shootdagger.%uuid of loop-player%} is 4:
			#teleport {Daggers.Location.%uuid of loop-player%} to loop-player

			teleport {Daggers.1.%uuid of loop-player%} to location 1.5 blocks infront and 0.1 metres right and 0.6 metres above loop-player
			teleport {Daggers.2.%uuid of loop-player%} to location 1.3 blocks infront and 0.8 metres left and 0.6 metres above loop-player
			teleport {Daggers.3.%uuid of loop-player%} to location 1.3 blocks infront and 1 metres right and 0.6 metres above loop-player
			teleport {Daggers.4.%uuid of loop-player%} to location 0.35 blocks infront and 1.1 metres left and 0.6 metres above loop-player

		else if {Shootdagger.%uuid of loop-player%} is 3:
			#teleport {Daggers.Location.%uuid of loop-player%} to loop-player

			teleport {Daggers.1.%uuid of loop-player%} to location 1.5 blocks infront and 0.1 metres right and 0.6 metres above loop-player
			teleport {Daggers.2.%uuid of loop-player%} to location 1.3 blocks infront and 0.8 metres left and 0.6 metres above loop-player
			teleport {Daggers.3.%uuid of loop-player%} to location 1.3 blocks infront and 1 metres right and 0.6 metres above loop-player


		else if {Shootdagger.%uuid of loop-player%} is 2:
			#teleport {Daggers.Location.%uuid of loop-player%} to loop-player



			teleport {Daggers.1.%uuid of loop-player%} to location 1.5 blocks infront and 0.1 metres right and 0.6 metres above loop-player
			teleport {Daggers.2.%uuid of loop-player%} to location 1.3 blocks infront and 0.8 metres left and 0.6 metres above loop-player


		else if {Shootdagger.%uuid of loop-player%} is 1:
			#teleport {Daggers.Location.%uuid of loop-player%} to loop-player

			teleport {Daggers.1.%uuid of loop-player%} to location 1.5 blocks infront and 0.1 metres right and 0.6 metres above loop-player







on left click:
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
			set {_uuid} to uuid of player
			if {Shootdagger.%{_uuid}%} > 0:
				if {Shootdagger.%{_uuid}%} is 5:
					kill {Daggers.5.%{_uuid}%}
					shootdagger5(player)
					remove 1 from {Shootdagger.%{_uuid}%}
					set {Daggers.5.%{_uuid}%.shotdagger} to true

				else if {Shootdagger.%{_uuid}%} is 4:
					kill {Daggers.4.%{_uuid}%}
					shootdagger4(player)
					remove 1 from {Shootdagger.%{_uuid}%}
					set {Daggers.4.%{_uuid}%.shotdagger} to true

				else if {Shootdagger.%{_uuid}%} is 3:
					kill {Daggers.3.%{_uuid}%}
					shootdagger3(player)
					remove 1 from {Shootdagger.%{_uuid}%}
					set {Daggers.3.%{_uuid}%.shotdagger} to true

				else if {Shootdagger.%{_uuid}%} is 2:
					kill {Daggers.2.%{_uuid}%}
					shootdagger2(player)
					remove 1 from {Shootdagger.%{_uuid}%}
					set {Daggers.2.%{_uuid}%.shotdagger} to true

				else if {Shootdagger.%{_uuid}%} is 1:
					kill {Daggers.1.%{_uuid}%}
					shootdagger1(player)
					remove 1 from {Shootdagger.%{_uuid}%}
					set {Daggers.1.%{_uuid}%.shotdagger} to true
					wait 1 tick
					set {Daggers.on.%{_uuid}%} to false
					set bar progress of {Dagger.Bar.%{_uuid}%} to 0
					remove player from bossbar players of {Dagger.Bar.%{_uuid}%}


on damage:
	if attacker's held item is prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		set {_uuid} to uuid of attacker
		if {-Astra.Power3.Projection.Activated.%{_uuid}%} is not true:
			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is false:
				if {Bliss.GemHealth.%{_uuid}%} > 3:
					set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
					set {Astra.Power1.Daggers.Second.%{_uuid}%} to 45
					set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
				if {Bliss.GemHealth.%{_uuid}%} is 3:
					set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 1
					set {Astra.Power1.Daggers.Second.%{_uuid}%} to 15
					set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
				if {Bliss.GemHealth.%{_uuid}%} < 3:
					set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 1
					set {Astra.Power1.Daggers.Second.%{_uuid}%} to 45
					set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

				set {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%} to true
				set {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%.Spect} to victim

				set attacker's gamemode to spectator

				set spectator target of attacker to victim

		else if attacker's held item is amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			send "<##A01FFF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to attacker


on right click:
	if {Astra.Power1.Daggers.ActivatedSpec.%uuid of player%} is true:
		set {Astra.Power1.Daggers.ActivatedSpec.%uuid of player%} to false
		set {_uuid} to uuid of player
		set player's gamemode to survival
		set {_v} to {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%.Spect}
	
		loop 10 times:
			play sound "entity.warden.nearby_closer" for {_v}
		if {Gem.%{_v}'s uuid%} is "Strength":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##F10303>&lsᴛʀᴇɴɢᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Speed":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FEFD17>&lsᴘᴇᴇᴅ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Life":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE04B4>&lʟɪғᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Puff":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##EFEFEF>&lᴘᴜғғ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Fire":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE8120>&lғɪʀᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Wealth":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##0EC912>&lᴡᴇᴀʟᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Astra":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##A01FFF>&lᴀsᴛʀᴀ <##B2FFF6>for &e30s" to player
		
		add 10 to {Disabled.%uuid of {_v}%}



on left click:
	if {Astra.Power1.Daggers.ActivatedSpec.%uuid of player%} is true:
		set {Astra.Power1.Daggers.ActivatedSpec.%uuid of player%} to false
		set {_uuid} to uuid of player
		set player's gamemode to survival
		set {_v} to {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%.Spect}
	
		loop 10 times:
			play sound "entity.warden.nearby_closer" for {_v}
		if {Gem.%{_v}'s uuid%} is "Strength":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##F10303>&lsᴛʀᴇɴɢᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Speed":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FEFD17>&lsᴘᴇᴇᴅ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Life":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE04B4>&lʟɪғᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Puff":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##EFEFEF>&lᴘᴜғғ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Fire":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE8120>&lғɪʀᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Wealth":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##0EC912>&lᴡᴇᴀʟᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Astra":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##A01FFF>&lᴀsᴛʀᴀ <##B2FFF6>for &e30s" to player
		
		add 10 to {Disabled.%uuid of {_v}%}
			

on spectate stop:
	set {_uuid} to uuid of player
	if {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%} is true:
		set player's gamemode to survival
		set {_v} to {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%.Spect}
	
		loop 10 times:
			play sound "entity.warden.nearby_closer" for {_v}
		if {Gem.%{_v}'s uuid%} is "Strength":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##F10303>&lsᴛʀᴇɴɢᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Speed":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FEFD17>&lsᴘᴇᴇᴅ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Life":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE04B4>&lʟɪғᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Puff":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##EFEFEF>&lᴘᴜғғ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Fire":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##FE8120>&lғɪʀᴇ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Wealth":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##0EC912>&lᴡᴇᴀʟᴛʜ <##B2FFF6>for &e30s" to player

		else if {Gem.%{_v}'s uuid%} is "Astra":
			send "<##A01FFF>🔮 <##B2FFF6>You haunted and disabled &e%{_v}%'s <##A01FFF>&lᴀsᴛʀᴀ <##B2FFF6>for &e30s" to player
		
		add 10 to {Disabled.%uuid of {_v}%}
		
on disconnect:
	set {_uuid} to uuid of player
	if {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%} is true:
		set player's gamemode to survival
		set {_v} to {Astra.Power1.Daggers.ActivatedSpec.%{_uuid}%.Spect}
		add 10 to {Disabled.%uuid of {_v}%}

function AstraCircle(s: number, p: entity):
	AstraCircleLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 1
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(rgb(160, 31, 255), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}



function AstraCircleLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 3  # Adjust the angle increment
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
		make 1 of dust using dustOption(rgb(160, 31, 255), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}


function AstraCirclelast(s: number, p: entity):
	AstraCirclelastLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 1.5
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
			make 1 of dust using dustOption(rgb(160, 31, 255), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}
		wait 0.3 seconds


function AstraCirclelastLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 3  # Adjust the angle increment
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
			make 1 of dust using dustOption(rgb(160, 31, 255), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}
		wait 0.3 seconds

on left click:
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
			set {_uuid} to uuid of player
			if {Disabled.%{_uuid}%} < 1:
				set {_uuid} to uuid of player
				if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
					if {-Astra.Power3.Projection.Activated.%{_uuid}%} is not true:
						if {Daggers.on.%{_uuid}%} is false:
							set {_message} to {Astra.Power1.Daggers.Display.%{_uuid}%}
							replace "&b" and "🔪" with "" in {_message}
							send "<##A01FFF>🔮 &cYour <##C7C7C7>Unbounded &cskill is on cooldown for<##A01FFF>%{_message}% <##C7C7C7>seconds"

				if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is false:
					if {Shootdagger.%{_uuid}%} is not set:
						set {Shootdagger.%{_uuid}%} to 0

					if {Daggers.on.%{_uuid}%} is false:
						if {-Astra.Power3.Projection.Activated.%{_uuid}%} is not true:
							set {Daggers.on.%{_uuid}%} to true
							set {Shootdagger.%{_uuid}%} to 5
							set {_uuid} to uuid of player
							set bar progress of {Dagger.Bar.%{_uuid}%} to 100
							set {Dagger.Bar.%{_uuid}%} to boss bar with id "%{_uuid}%sdaggers" with title "&fDaggers" with color aqua with progress 100
							set bar style of {Dagger.Bar.%{_uuid}%} to solid bar




							add player to bossbar players of {Dagger.Bar.%{_uuid}%}

							if {Bliss.GemHealth.%{_uuid}%} > 3:
								set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 1
								set {Astra.Power1.Daggers.Second.%{_uuid}%} to 15
								set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
							if {Bliss.GemHealth.%{_uuid}%} is 3:
								set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 1
								set {Astra.Power1.Daggers.Second.%{_uuid}%} to 45
								set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
							if {Bliss.GemHealth.%{_uuid}%} < 3:
								set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 2
								set {Astra.Power1.Daggers.Second.%{_uuid}%} to 15
								set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

							set {Daggers.5.%{_uuid}%.shotdagger} to false
							set {Daggers.4.%{_uuid}%.shotdagger} to false
							set {Daggers.3.%{_uuid}%.shotdagger} to false
							set {Daggers.2.%{_uuid}%.shotdagger} to false
							set {Daggers.1.%{_uuid}%.shotdagger} to false

							#spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b}"
							#set {Daggers.Location.%{_uuid}%} to last spawned entity


							spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%player%dag"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
							set {Daggers.1.%{_uuid}%} to last spawned entity
							add last spawned entity to {Daggers::*}
							enchant {Daggers.1.%{_uuid}%}'s helmet with mending
							#broadcast "%{Daggers.1.%{_uuid}%}'s x coordinate% %{Daggers.1.%{_uuid}%}'s y coordinate% %{Daggers.1.%{_uuid}%}'s z coordinate%"

							spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%player%dag2"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
							set {Daggers.2.%{_uuid}%} to last spawned entity
							add last spawned entity to {Daggers::*}
							enchant {Daggers.2.%{_uuid}%}'s helmet with mending
							#broadcast "%{Daggers.1.%{_uuid}%}'s x coordinate% %{Daggers.1.%{_uuid}%}'s y coordinate% %{Daggers.1.%{_uuid}%}'s z coordinate%"


							spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%player%dag3"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
							set {Daggers.3.%{_uuid}%} to last spawned entity
							add last spawned entity to {Daggers::*}
							enchant {Daggers.3.%{_uuid}%}'s helmet with mending
							#broadcast "%{Daggers.1.%{_uuid}%}'s x coordinate% %{Daggers.1.%{_uuid}%}'s y coordinate% %{Daggers.1.%{_uuid}%}'s z coordinate%"



							spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%player%dag4"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
							set {Daggers.4.%{_uuid}%} to last spawned entity
							add last spawned entity to {Daggers::*}
							enchant {Daggers.4.%{_uuid}%}'s helmet with mending
							#broadcast "%{Daggers.1.%{_uuid}%}'s x coordinate% %{Daggers.1.%{_uuid}%}'s y coordinate% %{Daggers.1.%{_uuid}%}'s z coordinate%"


							spawn armor stand at location of player with nbt compound from "{Marker:1b,Invisible:1b,Tags:""%player%dag5"",ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f],Small:1b}"
							set {Daggers.5.%{_uuid}%} to last spawned entity
							add last spawned entity to {Daggers::*}
							enchant {Daggers.5.%{_uuid}%}'s helmet with mending
							#broadcast "%{Daggers.1.%{_uuid}%}'s x coordinate% %{Daggers.1.%{_uuid}%}'s y coordinate% %{Daggers.1.%{_uuid}%}'s z coordinate%"
		
		
		else if player's held item is amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
				send "<##A01FFF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player
					


every 1 tick:
	loop all offline players:

		if bar progress of {Dagger.Bar.%uuid of loop-offlineplayer%} > 0:
			remove 0.2 from bar progress of {Dagger.Bar.%uuid of loop-offlineplayer%}
			
		else:
			remove loop-offlineplayer from bossbar players of {Dagger.Bar.%uuid of loop-offlineplayer%}
			set {Daggers.1.%uuid of loop-offlineplayer%.shotdagger} to true
			set {Daggers.2.%uuid of loop-offlineplayer%.shotdagger} to true
			set {Daggers.3.%uuid of loop-offlineplayer%.shotdagger} to true
			set {Daggers.4.%uuid of loop-offlineplayer%.shotdagger} to true
			set {Daggers.5.%uuid of loop-offlineplayer%.shotdagger} to true
			set {Shootdagger.%uuid of loop-offlineplayer%} to 0

			set {Daggers.on.%uuid of loop-offlineplayer%} to false

			if {Daggers.5.%uuid of loop-offlineplayer%} is not {Daggers.5.%uuid of loop-offlineplayer%.real}:
				kill {Daggers.5.%uuid of loop-offlineplayer%}

			if {Daggers.4.%uuid of loop-offlineplayer%} is not {Daggers.4.%uuid of loop-offlineplayer%.real}:
				kill {Daggers.4.%uuid of loop-offlineplayer%}

			if {Daggers.3.%uuid of loop-offlineplayer%} is not {Daggers.3.%uuid of loop-offlineplayer%.real}:
				kill {Daggers.3.%uuid of loop-offlineplayer%}

			if {Daggers.2.%uuid of loop-offlineplayer%} is not {Daggers.2.%uuid of loop-offlineplayer%.real}:
				kill {Daggers.2.%uuid of loop-offlineplayer%}

			if {Daggers.1.%uuid of loop-offlineplayer%} is not {Daggers.1.%uuid of loop-offlineplayer%.real}:
				kill {Daggers.1.%uuid of loop-offlineplayer%}

		







every 1 tick:
	loop all entities:
		loop all entities in radius 1 of loop-entity:
			if loop-entity-1 is not loop-entity-2:
				if loop-entity-2 is a armor stand:
					if loop-entity-2's helmet is a nautilus shell:
						if loop-entity-2 is not {Daggers.1.%uuid of loop-entity-1%.real}:
							if loop-entity-2 is not {Daggers.2.%uuid of loop-entity-1%.real}:
								if loop-entity-2 is not {Daggers.3.%uuid of loop-entity-1%.real}:
									if loop-entity-2 is not {Daggers.4.%uuid of loop-entity-1%.real}:
										if loop-entity-2 is not {Daggers.5.%uuid of loop-entity-1%.real}:
											if loop-entity-2 is not {Daggers.1.%uuid of loop-entity-1%}:
												if loop-entity-2 is not {Daggers.2.%uuid of loop-entity-1%}:
													if loop-entity-2 is not {Daggers.3.%uuid of loop-entity-1%}:
														if loop-entity-2 is not {Daggers.4.%uuid of loop-entity-1%}:
															if loop-entity-2 is not {Daggers.5.%uuid of loop-entity-1%}:
																if loop-entity-1's helmet is not a nautilus shell:

																	loop {Daggers::*}:
																		if loop-entity-2 is loop-value-3:
																			set {_no} to true

																	loop all offline players:
																		if loop-entity-2 is {Daggers.1.%uuid of loop-offlineplayer%.real}:
																			if "%{Bliss.Trusted.%uuid of loop-offlineplayer%::*}%" contains "%loop-entity-1's uuid%":
																				set {_no} to true
																				send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to loop-offlineplayer

																		else if loop-entity-2 is {Daggers.2.%uuid of loop-offlineplayer%.real}:
																			if "%{Bliss.Trusted.%uuid of loop-offlineplayer%::*}%" contains "%loop-entity-1's uuid%":
																				set {_no} to true
																				send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to loop-offlineplayer

																		else if loop-entity-2 is {Daggers.3.%uuid of loop-offlineplayer%.real}:
																			if "%{Bliss.Trusted.%uuid of loop-offlineplayer%::*}%" contains "%loop-entity-1's uuid%":
																				set {_no} to true
																				send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to loop-offlineplayer

																		else if loop-entity-2 is {Daggers.4.%uuid of loop-offlineplayer%.real}:
																			if "%{Bliss.Trusted.%uuid of loop-offlineplayer%::*}%" contains "%loop-entity-1's uuid%":
																				set {_no} to true
																				send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to loop-offlineplayer

																		else if loop-entity-2 is {Daggers.5.%uuid of loop-offlineplayer%.real}:
																			if "%{Bliss.Trusted.%uuid of loop-offlineplayer%::*}%" contains "%loop-entity-1's uuid%":
																				set {_no} to true
																				send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to loop-offlineplayer
																		



																	if {_no} is not true:
																		set {_aa} to loop-entity-1
																		if {_aa}'s helmet is not a nautilus shell:
																			
																			if {-Astra.Power3.Projection.Activated.%{_aa}'s uuid%} is not true:
																				


																				if {_aa} is not npc:

																				
																					
																					add 10 to {Disabled.%uuid of loop-entity-1%}
																					damage loop-entity-1 by 0.00000000000001
																					
																					kill loop-entity-2

																					loop all offline players:
																						if loop-entity-2 is {Daggers.1.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.2.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.3.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.4.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.5.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"


																					if {_aa}'s gamemode is not creative or spectator:
																						set {_aa}'s health to {_aa}'s health - 3
																						damage {_aa} by 0.0001 hearts

																			else if {-Astra.Power3.Projection.Activated.%{_aa}'s uuid%} is not set:
																				


																				if {_aa} is not npc:

																				
																					
																					add 10 to {Disabled.%uuid of loop-entity-1%}
																					damage loop-entity-1 by 0.00000000000001
																					
																					kill loop-entity-2

																					loop all offline players:
																						if loop-entity-2 is {Daggers.1.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.2.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.3.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.4.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"

																						else if loop-entity-2 is {Daggers.5.%uuid of loop-offlineplayer%.real}:
																							set {LastAttacker.%loop-entity-2's uuid%} to "%uuid of loop-offlineplayer%"


																					if {_aa}'s gamemode is not creative or spectator:
																						set {_aa}'s health to {_aa}'s health - 3
																						damage {_aa} by 0.0001 hearts

																					
											











command /testdaggers <player>:
	permission: op
	trigger:
		set {_uuid} to uuid of arg-1
		add 10 to {Disabled.%{_uuid}%}



every 1 tick:
	loop all players:
		if lore of loop-player's held item contains "<##FFE4AB>ᴘᴀssɪᴠᴇs":
			if {Disabled.%uuid of loop-player%} > 0:
				if {Disabled.%uuid of loop-player%} is 0:

					send action bar "🔒 &8&lᴅɪsᴀʙʟᴇᴅ: %{_mess}%&&8&laReady" to loop-player

				else:

					send action bar "🔒 &8&lᴅɪsᴀʙʟᴇᴅ: %{Disabled.%uuid of loop-player%}%" to loop-player

		else if lore of loop-player's off hand item contains "<##FFE4AB>ᴘᴀssɪᴠᴇs":
			if {Disabled.%uuid of loop-player%} > 0:
				if {Disabled.%uuid of loop-player%} is 0:

					send action bar "🔒 &8&lᴅɪsᴀʙʟᴇᴅ: %{_mess}%&&8&laReady" to loop-player

				else:

					send action bar "🔒 &8&lᴅɪsᴀʙʟᴇᴅ: %{Disabled.%uuid of loop-player%}%" to loop-player


every 1 second:
	loop all players:
		if {Disabled.%uuid of loop-player%} > 0:
			remove 1 from {Disabled.%uuid of loop-player%}

	loop all players:
		if {Daggers.on.%uuid of loop-player%} is not set:
			set {Daggers.on.%uuid of loop-player%} to false


on damage:
	if victim has a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		chance of 10%
		cancel event
		apply invisibility to victim for 15 ticks
	if victim has a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		chance of 15%
		cancel event
		apply invisibility to victim for 15 ticks



on death:
	if victim is not {NokillMobs::*}:
		if attacker's off hand item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			if victim is not a player:
				loop 300 times:
					make 40 of dust using dustOption(rgb(160, 31, 255), 1) at location 1 block above victim with offset vector(0.2, 0.2, 0.2) with extra 0 with force

				set {Entity.%uuid of attacker%.tier1} to "%victim%"








			else:


					
		if attacker's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
			if victim is not a player:
				heal attacker by 2.5
				loop 300 times:
					make 40 of dust using dustOption(rgb(160, 31, 255), 1) at location 1 block above victim with offset vector(0.2, 0.2, 0.2) with extra 0 with force
				if {Entity.%uuid of attacker%} is 0 or 1:
					add 1 to {Entity.%uuid of attacker%}

					if {Entity.%uuid of attacker%} is 2:
						set {Entity.%uuid of attacker%.2} to "%victim%"
						

					if {Entity.%uuid of attacker%} is 1:
						set {Entity.%uuid of attacker%.1} to "%victim%"

					set {entity.%uuid of attacker%::*} to capitalizeFirst("%victim%")



				else:

					set {Entity.%uuid of attacker%.1} to {Entity.%uuid of attacker%.2}

					set {Entity.%uuid of attacker%.2} to "%victim%"

					set {entity.%uuid of attacker%::*} to capitalizeFirst("%victim%")



			else:

				heal attacker by 5



	
on right click:
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##FFD773>ɢᴇᴍ":
		if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
			if player is sneaking:
				if {Entity.%uuid of player%.2} is set:
					set {_e} to {Entity.%uuid of player%.2} parsed as entity type

					spawn {_e} at location 1 block above target block
					clear {Entity.%uuid of player%.2}
					set {Entity.%uuid of player%} to 1
					set {entity.%uuid of player%::*} to capitalizeFirst("%{Entity.%uuid of player%.1}%")
					add last spawned entity to {NokillMobs::*}

				else if {Entity.%uuid of player%.1} is set:
					set {_e} to {Entity.%uuid of player%.1} parsed as entity type
					spawn {_e} at location 1 block above target block
					clear {Entity.%uuid of player%.1}
					set {Entity.%uuid of player%} to 0
					clear {entity.%uuid of player%::*}
					add last spawned entity to {NokillMobs::*}


on right click:
	if player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		if lore of player's held item doesn't contain "&f&lᴜѕᴇʟᴇѕѕ":
			if player is sneaking:
				if {Entity.%uuid of player%.tier1} is set:
					set {_e} to {Entity.%uuid of player%.tier1} parsed as entity type
					spawn {_e} at location 1 block above target block
					clear {Entity.%uuid of player%.tier1}
					clear {entity.%uuid of player%::*}
					add last spawned entity to {NokillMobs::*}





function capitalizeFirst(text: texts) :: texts:
	loop {_text::*}:
		set {_first-char} to first character of loop-value
		set {_remaining} to last (length of loop-value - 1) characters of loop-value
		set {_output::%loop-index%} to "%{_first-char} in upper case%%{_remaining}%"
		return {_output::*}

command /fuckastra:
	permission: op
	trigger:
		set {Entity.%uuid of player%} to 0
		




