#puff powers

every 1 second:
	loop all players:
		loop all items in loop-player's inventory:
			if name of loop-slot contains "<##EFEFEF>&lᴘᴜғғ" or "<##ffcc26>&lGold Gem":
				#Breezy
				if {Puff.Power3.Breezy.Cooldown.%uuid of loop-player%} is true:
					if {Puff.Power3.Breezy.Minute.%uuid of loop-player%} is 0:
						set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &b%{Puff.Power3.Breezy.Second.%uuid of loop-player%}%s"

					else:
						set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &b%{Puff.Power3.Breezy.Minute.%uuid of loop-player%}%m %{Puff.Power3.Breezy.Second.%uuid of loop-player%}%s"		
				if {Puff.Power3.Breezy.Second.%uuid of loop-player%} is not set:
					set {Puff.Power3.Breezy.Second.%uuid of loop-player%} to 0
					set {Puff.Power3.Breezy.Minute.%uuid of loop-player%} to 0
					set {Puff.Power3.Breezy.Cooldown.%uuid of loop-player%} to true

				if {Puff.Power3.Breezy.Display.%uuid of loop-player%} is not set:
					set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &b%{Puff.Power3.Breezy.Minute.%uuid of loop-player%}%m %{Puff.Power3.Breezy.Second.%uuid of loop-player%}%s"
					
			
				if {Puff.Power3.Breezy.Cooldown.%uuid of loop-player%} is true:
					if {Puff.Power3.Breezy.Minute.%uuid of loop-player%} is 0:
						set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &b%{Puff.Power3.Breezy.Second.%uuid of loop-player%}%s"

					else:
						set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &b%{Puff.Power3.Breezy.Minute.%uuid of loop-player%}%m %{Puff.Power3.Breezy.Second.%uuid of loop-player%}%s"

				if {Puff.Power3.Breezy.Cooldown.%uuid of loop-player%} is true:
					remove 1 from {Puff.Power3.Breezy.Second.%uuid of loop-player%}

				if {Puff.Power3.Breezy.Second.%uuid of loop-player%} < 0:
					remove 1 from {Puff.Power3.Breezy.Minute.%uuid of loop-player%}
					set {Puff.Power3.Breezy.Second.%uuid of loop-player%} to 59
					
				if {Puff.Power3.Breezy.Minute.%uuid of loop-player%} < 0:
					set {Puff.Power3.Breezy.Cooldown.%uuid of loop-player%} to false
					set {Puff.Power3.Breezy.Display.%uuid of loop-player%} to "&f☁ &aReady!"

				#Enchanting

				if {Puff.Power2.Enchanting.Second.%uuid of loop-player%} is not set:
					set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true

				if {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} is not set:
					set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true

				if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is not set:
					set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true	
					set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to " &b%{Puff.Power2.Enchanting.Minute.%uuid of loop-player%}%m %{Puff.Power2.Enchanting.Second.%uuid of loop-player%}%s"

				if {Puff.Power2.Enchanting.Display.%uuid of loop-player%} is not set:
					set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 0
					set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true	

				if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is true:
					set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to "&b %{Puff.Power2.Enchanting.Minute.%uuid of loop-player%}%m %{Puff.Power2.Enchanting.Second.%uuid of loop-player%}%s"

				if {Puff.Power2.Enchanting.Display.%uuid of loop-player%} is not set:
					set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to " &b %{Puff.Power2.Enchanting.Minute.%uuid of loop-player%}%m %{Puff.Power2.Enchanting.Second.%uuid of loop-player%}%s"

				if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is true:
					if {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} is 0:
						set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to "&b %{Puff.Power2.Enchanting.Second.%uuid of loop-player%}%s"

					else:
						set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to "&b %{Puff.Power2.Enchanting.Minute.%uuid of loop-player%}%m %{Puff.Power2.Enchanting.Second.%uuid of loop-player%}%s"

				if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is true:
					remove 1 from {Puff.Power2.Enchanting.Second.%uuid of loop-player%}

				if {Puff.Power2.Enchanting.Second.%uuid of loop-player%} < 0:
					remove 1 from {Puff.Power2.Enchanting.Minute.%uuid of loop-player%}
					set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 59
					
				if {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} < 0:
					set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to false
					set {Puff.Power2.Enchanting.Display.%uuid of loop-player%} to " &aReady!"

				if loop-player's held item is prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
					if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is false:
						send "<##EFEFEF>🔮 <##B8FFFB>Auto Enchanting" to loop-player
						set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 14
						set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 59
						set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true
						loop all items in loop-player's inventory:
					
							if loop-slot-2 is a bow:
								enchant loop-slot-2 with power 5
								enchant loop-slot-2 with punch 2
							else if loop-slot-2 is a boots:
								enchant loop-slot-2 with feather falling 4

				
				if loop-player's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
					if {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} is false:
						send "<##EFEFEF>🔺 <##B8FFFB>Auto Enchanting" to loop-player
						set {Puff.Power2.Enchanting.Minute.%uuid of loop-player%} to 14
						set {Puff.Power2.Enchanting.Second.%uuid of loop-player%} to 59
						set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true
						set {Puff.Power2.Enchanting.Cooldown.%uuid of loop-player%} to true
						loop all items in loop-player's inventory:
						
							if loop-slot-2 is a bow:
								enchant loop-slot-2 with power 3
								enchant loop-slot-2 with punch 1



				#Dash





				if {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} is true:
					remove 1 from {Puff.Power1.Dash.Second.%uuid of loop-player%}


				
				if {Puff.Power1.Dash.Second.%uuid of loop-player%} < 0:
					remove 1 from {Puff.Power1.Dash.Minute.%uuid of loop-player%}
					set {Puff.Power1.Dash.Second.%uuid of loop-player%} to 59


				if {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} is true:
					if {Puff.Power1.Dash.Minute.%uuid of loop-player%} is 0:
						set {Puff.Power1.Dash.Display.%uuid of loop-player%} to "&f⏫ &b%{Puff.Power1.Dash.Second.%uuid of loop-player%}%s"

					else:
						set {Puff.Power1.Dash.Display.%uuid of loop-player%} to "&f⏫ &b%{Puff.Power1.Dash.Minute.%uuid of loop-player%}%m %{Puff.Power1.Dash.Second.%uuid of loop-player%}%s"


				if {Puff.Power1.Dash.Second.%uuid of loop-player%} is not set:
					set {Puff.Power1.Dash.Second.%uuid of loop-player%} to 0
					set {Puff.Power1.Dash.Minute.%uuid of loop-player%} to 0

				if {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} is not set:
					set {Puff.Power1.Dash.Second.%uuid of loop-player%} to 0
					set {Puff.Power1.Dash.Minute.%uuid of loop-player%} to 0
					set {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} to true	

				if {Puff.Power1.Dash.Display.%uuid of loop-player%} is not set:
					set {Puff.Power1.Dash.Second.%uuid of loop-player%} to 0
					set {Puff.Power1.Dash.Minute.%uuid of loop-player%} to 0
					set {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} to true	


				if {Puff.Power1.Dash.Display.%uuid of loop-player%} is not set:
					set {Puff.Power1.Dash.Display.%uuid of loop-player%} to "&f⏫ &b%{Puff.Power1.Dash.Minute.%uuid of loop-player%}%m %{Puff.Power1.Dash.Second.%uuid of loop-player%}%s"



				if {Puff.Power1.Dash.Minute.%uuid of loop-player%} < 0:
					set {Puff.Power1.Dash.Cooldown.%uuid of loop-player%} to false
					set {Puff.Power1.Dash.Display.%uuid of loop-player%} to "&f⏫ &aReady!"








				#Doublejump





				if {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} is true:
					remove 1 from {Puff.Power4.Doublejump.Second.%uuid of loop-player%}


				
				if {Puff.Power4.Doublejump.Second.%uuid of loop-player%} < 0:
					remove 1 from {Puff.Power4.Doublejump.Minute.%uuid of loop-player%}
					set {Puff.Power4.Doublejump.Second.%uuid of loop-player%} to 59



				if {Puff.Power4.Doublejump.Second.%uuid of loop-player%} is not set:
					set {Puff.Power4.Doublejump.Second.%uuid of loop-player%} to 0
					set {Puff.Power4.Doublejump.Minute.%uuid of loop-player%} to 0

				if {Puff.Power4.Doublejump.Minute.%uuid of loop-player%} is not set:
					set {Puff.Power4.Doublejump.Second.%uuid of loop-player%} to 0
					set {Puff.Power4.Doublejump.Minute.%uuid of loop-player%} to 0
					set {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} to false

				if {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} is not set:
					set {Puff.Power4.Doublejump.Second.%uuid of loop-player%} to 0
					set {Puff.Power4.Doublejump.Minute.%uuid of loop-player%} to 0
					set {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} to false





				if {Puff.Power4.Doublejump.Minute.%uuid of loop-player%} < 0:
					set {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} to false
					



every 1 tick:
	loop all players:
		if {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} is false:
			set flight mode of loop-player to true
		else if {Puff.Power4.Doublejump.Cooldown.%uuid of loop-player%} is true:
			set flight mode of loop-player to false



on flight toggle:
	if player's gamemode is not creative:
		if player's off hand item is a amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			cancel event
			set {_uuid} to uuid of player
			if {Puff.Power4.Doublejump.Cooldown.%{_uuid}%} is not true:
				if {Disabled.%{_uuid}%} < 1:
					draw 5 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					push player forward at speed 0.7
					push player up at speed 0.5
					set {Puff.Power4.Doublejump.Second.%{_uuid}%} to 5
					set {Puff.Power4.Doublejump.Minute.%{_uuid}%} to 0
					set {Puff.Power4.Doublejump.Cooldown.%{_uuid}%} to true
					send "<##EFEFEF>🔺 <##B8FFFB>You have used <##EFEFEF>Double Jump <##B8FFFB>now on cooldown for <##EFEFEF>5 seconds" to player
		if player's off hand item is a prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			cancel event
			set {_uuid} to uuid of player
			if {Puff.Power4.Doublejump.Cooldown.%{_uuid}%} is not true:
				if {Disabled.%{_uuid}%} < 1:
					push player forward at speed 0.7
					push player up at speed 0.5
					set {Puff.Power4.Doublejump.Second.%{_uuid}%} to 5
					set {Puff.Power4.Doublejump.Minute.%{_uuid}%} to 0
					set {Puff.Power4.Doublejump.Cooldown.%{_uuid}%} to true	
					send "<##EFEFEF>🔮 <##B8FFFB>You have used <##EFEFEF>Double Jump <##B8FFFB>now on cooldown for <##EFEFEF>5 seconds" to player
					draw 5 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 2 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 3 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 2 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 4 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 3 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 3 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 2 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 2 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 1 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
					wait 1 ticks
					draw 2 cloud at player with offset vector(0.1, 0.1, 0.1) with extra 0 with force
			
on damage:
	if damage cause is fall:
		if victim's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			cancel event
		if victim's off hand item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			cancel event
		if victim's offhand item is prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			cancel event
		if victim's held item is prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			cancel event

	if damage cause is contact:
		if victim's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			cancel event
		if victim's off hand item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			cancel event
		if victim's offhand item is prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			cancel event
		if victim's held item is prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			cancel event



on damage:
	set {_uuid} to uuid of attacker
	if {Disabled.%{_uuid}%} < 1:
		if attacker's held item is a prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			if {Puff.Power3.Breezy.Cooldown.%{_uuid}%} is not true:
				if "%{Bliss.Trusted.%{_uuid}%::*}%" contains "%victim's uuid%":

					send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to attacker

				else:
					wait 1 ticks
					push victim up at speed 6
					send "<##EFEFEF>🔮 <##B8FFFB>You have been affected with &f☁Breezy bash <##B8FFFB>by <##EFEFEF>%attacker%" to victim
					send "<##EFEFEF>🔮 <##B8FFFB>You have activated &f☁Breezy bash <##B8FFFB>skill on <##EFEFEF>%victim%" to attacker
					if {Bliss.GemHealth.%{_uuid}%} >= 4:	
						set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 0
						set {Puff.Power3.Breezy.Second.%{_uuid}%} to 45
						set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} is 3:	
						set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
						set {Puff.Power3.Breezy.Second.%{_uuid}%} to 15
						set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} < 3:	
						set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
						set {Puff.Power3.Breezy.Second.%{_uuid}%} to 35
						set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
					wait 1.25 seconds
					push victim down at speed 9
					set {PuffLine.%attacker's uuid%.%victim's uuid%} to true
					wait 20 seconds
					set {PuffLine.%attacker's uuid%.%victim's uuid%} to false

			else:
				set {_uuid} to uuid of attacker
				if {Puff.Power3.Breezy.Minute.%{_uuid}%} < 1:
					send "<##EFEFEF>🔮 &cYour &f☁<##EFEFEF>Breezy bash &cskill is on cooldown for <##EFEFEF>%{Puff.Power3.Breezy.Second.%{_uuid}%}%s" to attacker
				else:
					send "<##EFEFEF>🔮 &cYour &f☁<##EFEFEF>Breezy bash &cskill is on cooldown for <##EFEFEF>%{Puff.Power3.Breezy.Minute.%{_uuid}%}%m %{Puff.Power3.Breezy.Second.%{_uuid}%}%s" to attacker

					
		else if attacker's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			send "<##EFEFEF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to attacker
				
on left click:
	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if player's held item is a prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			if {Puff.Power3.Breezy.Cooldown.%{_uuid}%} is not true:

				if lore of player's held item contains "<##57FFC7>Pristine":
					set {_num} to 5
					set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 0
					set {Puff.Power3.Breezy.Second.%{_uuid}%} to 45
					set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

				else:
					if lore of player's held item contains "<##57FF8F>Scratched":
						set {_num} to 4
						set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 0
						set {Puff.Power3.Breezy.Second.%{_uuid}%} to 45
						set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

					else:

						if lore of player's held item contains "<##7958DB>Cracked":
							set {_num} to 3
							set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
							set {Puff.Power3.Breezy.Second.%{_uuid}%} to 15
							set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
					
						else:

							if lore of player's held item contains "<##FFC929>Damaged":
								set {_num} to 2
								set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
								set {Puff.Power3.Breezy.Second.%{_uuid}%} to 15
								set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

							else:

								if lore of player's held item contains "<##FF1111>Ruined":
									set {_num} to 1
									set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
									set {Puff.Power3.Breezy.Second.%{_uuid}%} to 35
									set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
									
								else:

									if lore of player's held item contains "&7Broken":
										set {_num} to 1
										set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
										set {Puff.Power3.Breezy.Second.%{_uuid}%} to 35
										set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

									else:

										if {Bliss.GemHealth.%{_uuid}%} > 5:
											set {_num} to 5
											set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 0
											set {Puff.Power3.Breezy.Second.%{_uuid}%} to 45
											set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
					

										else:

											if {Bliss.GemHealth.%{_uuid}%} is 5:
												set {_num} to 4
												set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 0
												set {Puff.Power3.Breezy.Second.%{_uuid}%} to 45
												set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true
						
											else:

												if {Bliss.GemHealth.%{_uuid}%} is 4:
													set {_num} to 3
													set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
													set {Puff.Power3.Breezy.Second.%{_uuid}%} to 15
													set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

												else:
										
													if {Bliss.GemHealth.%{_uuid}%} is 3:
														set {_num} to 2
														set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
														set {Puff.Power3.Breezy.Second.%{_uuid}%} to 15
														set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

													else:

														if {Bliss.GemHealth.%{_uuid}%} is 2:
															set {_num} to 1
															set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
															set {Puff.Power3.Breezy.Second.%{_uuid}%} to 35
															set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true	
															
														else:

															if {Bliss.GemHealth.%{_uuid}%} is 1:
																set {_num} to 1
																set {Puff.Power3.Breezy.Minute.%{_uuid}%} to 1
																set {Puff.Power3.Breezy.Second.%{_uuid}%} to 35
																set {Puff.Power3.Breezy.Cooldown.%{_uuid}%} to true

						
				send "<##EFEFEF>🔮 <##B8FFFB>You have activated group &f☁<##EFEFEF>Breezy Bash <##B8FFFB>skill &7(radius %{_num}%)" to player
				set {_s} to 1
				loop {_num} + {_num} times:

					if loop-value is not {_num} + {_num}:
						PuffCircle({_s}, player)
				
						add 0.5 to {_s}

					else:
						PuffCirclelast({_s}, player)

				set {_puffholder} to player
				loop all entities within {_num} blocks of the player:
					if loop-entity is not {_puffholder}:
						if "%{Bliss.Trusted.%{_uuid}%::*}%" does not contain "%loop-entity's uuid%":
							send "<##EFEFEF>🔮 <##B8FFFB>You have been affected with &f☁<##EFEFEF>Breezy Bash <##B8FFFB>by <##EFEFEF>%{_puffholder}%" to loop-entity
							set {_p} to loop-entity
							set {_direction} to vector between {_puffholder} and {_p}

							push {_p} {_direction} at speed 3
							push {_p} up at speed 1

						else:
							send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to {_puffholder}

		else if player's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			send "<##EFEFEF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player





function PuffCircle(s: number, p: entity):
	PuffCircleLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 1
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(rgb(239, 239, 239), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}



function PuffCircleLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 3  # Adjust the angle increment
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
		make 1 of dust using dustOption(rgb(239, 239, 239), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}


function PuffCirclelast(s: number, p: entity):
	PuffCirclelastLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 1.5
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
			make 1 of dust using dustOption(rgb(239, 239, 239), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}
		wait 0.3 seconds


function PuffCirclelastLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 3  # Adjust the angle increment
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
			make 1 of dust using dustOption(rgb(239, 239, 239), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}
		wait 0.3 seconds



every 1 tick:
	loop all players:
		loop all entities:
			if {PuffLine.%loop-player-1's uuid%.%loop-entity-2's uuid%} is true:
				set {_v} to vector from loop-player-1's head to loop-entity-2's head
				set vector length of {_v} to 0.1
				set {_loc} to the location 0.7 meters under loop-player-1's head
				loop (distance between {_loc} and loop-entity-2) / 0.1 times:

					draw 1 dust using dustOption(rgb(239, 239, 239), 1) at {_loc} with force
					draw 1 dust_color_transition using dustTransition(black, black, 1) at {_loc} with force
					set {_loc} to {_loc} ~ {_v}

on right click:
	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if player's held item is a prismarine shard named "<##EFEFEF>&lᴘᴜғғ &r<##FFD773>ɢᴇᴍ":
			
			if {Puff.Power1.Dash.Cooldown.%{_uuid}%} is not true:
				set {Puff.Power1.Dash.Second.%{_uuid}%} to 30
				set {Puff.Power1.Dash.Minute.%{_uuid}%} to 0
				set {Puff.Power1.Dash.Cooldown.%{_uuid}%} to true
				push player forward at speed 5
				send "<##EFEFEF>🔮 <##B8FFFB>You have activated &f⏫<##EFEFEF>Dash <##B8FFFB>skill" to player
				set {Dash...%player%} to true
				add 2 to {-PuffParticle.%uuid of player%}
				wait 8 seconds
				set {Dash...%player%} to false
			else:
				set {_uuid} to uuid of player
				if {Puff.Power1.Dash.Minute.%{_uuid}%} is 0:
					send "<##EFEFEF>🔮 &cYour &f⏫<##EFEFEF>Dash &cskill is on cooldown for <##efefef>%{Puff.Power1.Dash.Second.%{_uuid}%}%s" to player
				else:
					send "<##EFEFEF>🔮 &cYour &f⏫<##EFEFEF>Dash &cskill is on cooldown for <##efefef>%{Puff.Power1.Dash.Minute.%{_uuid}%}%m %{Puff.Power1.Dash.Second.%{_uuid}%}%s" to player

		else if player's held item is amethyst shard named "<##EFEFEF>&lᴘᴜғғ &r<##C7C7C7>ɢᴇᴍ":
			send "<##EFEFEF>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

every 1 tick:
	loop all players:
		if {-PuffParticle.%uuid of loop-player%} > 0:
			make 5 of cloud at location of loop-player with extra 0

every 1 second:
	loop all players:
		if {-PuffParticle.%uuid of loop-player%} > 0:
			remove 1 from {-PuffParticle.%uuid of loop-player%}