on right click:

	if player's held item is a nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		increasenergy(player)


on right click:

	if player's held item is a nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 2 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 3 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 4 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 5 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 6 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 7 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 8 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 9 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 10 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 11 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 12 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 13 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 14 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		increasenergy(player)


on right click:

	if player's held item is 15 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 16 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 17 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 18 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 19 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 20 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 21 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 22 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 23 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 24 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 25 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 26 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 27 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 28 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 29 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 30 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 31 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 32 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 33 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 34 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 35 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 36 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 37 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 38 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 39 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 40 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 41 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 42 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 43 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 44 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 45 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 46 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 47 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 48 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 49 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 50 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 51 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 52 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 53 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 54 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 55 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 56 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 57 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 58 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 59 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 60 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 61 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 62 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 63 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		set {_uuid} to uuid of player
		increasenergy(player)


on right click:

	if player's held item is 64 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ":
		increasenergy(player)











































function increasenergy(p: player):
	set {_uuid} to uuid of {_p}

	if {Bliss.GemHealth.%{_uuid}%} < 10:
		remove 1 of nautilus shell with custom model data 300 named "<##96FFD9>&lᴇɴᴇʀɢʏ <##FFE4AB>ɪɴ ᴀ ʙᴏᴛᴛʟᴇ" from {_p}'s inventory
		add 1 to {Bliss.GemHealth.%{_uuid}%}

		if {Bliss.GemHealth.%{_uuid}%} is 10:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine &f+ <##96FFD9>5" to {_p}
			setenergy({_p}, 10)

		if {Bliss.GemHealth.%{_uuid}%} is 9:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine &f+ <##96FFD9>4" to {_p}
			setenergy({_p}, 9)

		if {Bliss.GemHealth.%{_uuid}%} is 8:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine &f+ <##96FFD9>3" to {_p}
			setenergy({_p}, 8)

		if {Bliss.GemHealth.%{_uuid}%} is 7:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine &f+ <##96FFD9>2" to {_p}
			setenergy({_p}, 7)

		if {Bliss.GemHealth.%{_uuid}%} is 6:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine &f+" to {_p}
			setenergy({_p}, 6)

		if {Bliss.GemHealth.%{_uuid}%} is 5:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##01F5C3>Pristine" to {_p}
			setenergy({_p}, 5)

		if {Bliss.GemHealth.%{_uuid}%} is 4:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##9DF200>Scratched" to {_p}
			setenergy({_p}, 4)

		if {Bliss.GemHealth.%{_uuid}%} is 3:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##3F00D1>Cracked" to {_p}
			setenergy({_p}, 3)

		if {Bliss.GemHealth.%{_uuid}%} is 2:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##FFD02A>Damaged" to {_p}
			setenergy({_p}, 2)

		if {Bliss.GemHealth.%{_uuid}%} is 1:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at <##F10303>Ruined" to {_p}
			setenergy({_p}, 1)
		
		if {Bliss.GemHealth.%{_uuid}%} is 0:
			send "<##FFD773>🔮 <##96FFD9>&lᴇɴᴇʀɢʏ &fabosrbed, your gem is now at &7Broken" to {_p}
			setenergy({_p}, 0)

	
				
function setenergy(p: player, e: number):
	set {_onecycle} to false
	loop all items in {_p}'s inventory:
		if {_onecycle} is false:
			if string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-slot is set:
				set {_id} to string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-slot
				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "astra":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Astra"
						set loop-slot to getgembackwithoutid("astra", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Astra"
						set loop-slot to getgembackwithoutid("astra", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "fire":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Fire"
						set loop-slot to getgembackwithoutid("fire", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Fire"
						set loop-slot to getgembackwithoutid("fire", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "life":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Life"
						set loop-slot to getgembackwithoutid("life", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Life"
						set loop-slot to getgembackwithoutid("life", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "puff":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Puff"
						set loop-slot to getgembackwithoutid("puff", 2, {_e}, 3, 3, {_id})
					
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Puff"
						set loop-slot to getgembackwithoutid("puff", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "speed":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Speed"
						set loop-slot to getgembackwithoutid("speed", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Speed"
						set loop-slot to getgembackwithoutid("speed", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "strength":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Strength"
						set loop-slot to getgembackwithoutid("strength", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Strength"
						set loop-slot to getgembackwithoutid("strength", 1, {_e}, 3, 3, {_id})

				if string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-slot is "wealth":
					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 2:
						set {_gem} to "Wealth"
						set loop-slot to getgembackwithoutid("wealth", 2, {_e}, 3, 3, {_id})

					if int tag "PublicBukkitValues;blissgems:gem-tier" of nbt compound of loop-slot is 1:
						set {_gem} to "Wealth"
						set loop-slot to getgembackwithoutid("wealth", 1, {_e}, 3, 3, {_id})
