#speed powers

every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
			if {-Speed.SpeedStorm.Activated.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%} is not true:
				apply speed 2 without particles to loop-player for 2 seconds replacing the existing effect

		if loop-player's held item is a amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
			if {-Speed.SpeedStorm.Activated.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%} is not true:
				apply speed 2 without particles to loop-player for 2 seconds replacing the existing effect

		if loop-player's off hand item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
			if {-Speed.SpeedStorm.Activated.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%} is not true:
				apply speed 3 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 1 without particles to loop-player for 2 seconds replacing the existing effect

		if loop-player's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
			if {-Speed.SpeedStorm.Activated.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-player's held item%} is not true:
				apply speed 3 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 1 without particles to loop-player for 2 seconds replacing the existing effect



every 1 second:
	loop all players:
		loop all items in loop-player's inventory:
			if nbt compound of loop-item has tag "PublicBukkitValues;blissgems:gem-type":
				if "%string tag "PublicBukkitValues;blissgems:gem-type" of nbt compound of loop-item%" is "speed":
					if {_nomultiple::*} doesn't contain string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item:
						add string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item to {_nomultiple::*}
						#SpeedStorm
						
						if {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false



						if {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}



						if {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							remove 1 from {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
							set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59
							
						if {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
							set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
					


						#Enchanting



										

					

						if {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to true





						if {-Speed.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}


						
						if {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							remove 1 from {-Speed.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
							set {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59
							
							
						if {-Speed.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Speed.Power2.Enchanting.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
							set {-Speed.Power2.Enchanting.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power2.Enchanting.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0




						#SlothSedative



						if {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is not set:
							set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false


						if {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} is true:
							remove 1 from {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}


						
						if {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							remove 1 from {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%}
							set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 59




						if {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} < 0:
							set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to false
							set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0
							set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of loop-item%} to 0




on world save:
	loop all offline players:
		set {Speed.Attributesets.%uuid of loop-offlineplayer%} to {-Speed.Attributesets.%uuid of loop-offlineplayer%}



on skript start:
	loop all offline players:
		set {-Speed.Attributesets.%uuid of loop-offlineplayer%} to {Speed.Attributesets.%uuid of loop-offlineplayer%}


on left click:
	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if player's held item is amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
			send "<##FEFD17>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

		if player's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
			set {_uuid} to uuid of player
			if {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} is false:







				if lore of player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":
					set {_num} to 5
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##57FF8F>Scratched":
					set {_num} to 4
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##7958DB>Cracked":
					set {_num} to 3
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 5
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true
			
				else if lore of player's held item contains "<##FFC929>Damaged":
					set {_num} to 2
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 7
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##FF1111>Ruined":
					set {_num} to 1
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 7
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true
					
				else if lore of player's held item contains "&7Broken":
					set {_num} to 1
					set {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 7
					set {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 59
					set {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

							
					
				send "<##FEFD17>🔮 <##B8FFFB>You have used group &f🎯<##FEFD17>Sloth's Sedative &7(radius %{_num}%)" to player

				set {_s} to 1
				loop {_num} + {_num} times:

					if loop-value is not {_num} + {_num}:
						SpeedCircle({_s}, player)
				
						add 0.5 to {_s}

					else:
						SpeedCirclelast({_s}, player)



				set {_speedholder} to player
				loop all entities within {_num} blocks of the player:
					if loop-entity is not {_speedholder}:
						if "%{Bliss.Trusted.%{_uuid}%::*}%" does not contain "%loop-entity's uuid%":
							send "<##FEFD17>🔮 <##B8FFFB>You have been affected by group &f🎯<##FEFD17>Sloth's Sedative <##B8FFFB>by <##FEFD17>%{_speedholder}%" to loop-entity
							apply potion of slowness of tier 3 to loop-entity for 30 seconds

							if loop-entity is a player:
								Silentexec("attribute %loop-entity% minecraft:generic.attack_speed base set 3.2")
								set {-Speed.Attributesets.%loop-entity's uuid%} to 30

							remove all potions from loop-entity

						else:
							send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to {_speedholder}

			else:
				set {_uuid} to uuid of player
				loop {-Speed.Power1.SlothSedative.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} times:
					add 60 to {_scoresl}

				add {-Speed.Power1.SlothSedative.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to {_scoresl}

				set {_secsl} to 0
				set {_minsl} to 0
				loop {_scoresl} times:
					add 1 to {_secsl}
					if {_secsl} is 60:
						add 1 to {_minsl}
						set {_secsl} to 0

				

				if {_secsl} is 0:
					if {_minsl} > 0:
						set {_sl} to "&b%{_minsl}%m"
	

				else if {_minsl} > 0:
					set {_sl} to "&b%{_minsl}%m %{_secsl}%s"					

				else:
					set {_sl} to "&b%{_secsl}%s"

				if {_scoresl} is 0:
					set {_sl} to "&aReady!"

				replace all "&b" and "🎯 " with "" in {_sl}
				send "<##FEFD17>🔮 <##FD8988>Your &f🎯<##FEFD17>Sloth's Sedative <##FD8988>skill is on cooldown for <##FEFD17>%{_sl}%" to player







		


on damage:
	set {_uuid} to uuid of attacker
	if {Disabled.%{_uuid}%} < 1:
		if attacker's held item is amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
			send "<##FEFD17>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to attacker


		if attacker's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
			
			if {-Speed.Power1.SlothSedative.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of attacker's held item%} is false:
				if "%{Bliss.Trusted.%{_uuid}%::*}%" contains "%victim's uuid%":

					send "<##FFD773>🔮 &fYou cannout cast negative skills on allies!" to attacker

				else:
					send "<##FEFD17>🔮 <##B8FFFB>You have used &f🎯<##FEFD17>Sloth's Sedative <##B8FFFB>on <##FEFD17>%victim%" to attacker
					set {_speedholder} to attacker
					send "<##FEFD17>🔮 <##B8FFFB>You have been affected with &f🎯<##FEFD17>Sloth's Sedative <##B8FFFB>by <##FEFD17>%{_speedholder}%" to victim
					


					apply potion of slowness of tier 4 to victim for 40 seconds

					if victim is a player:
						Silentexec("attribute %victim% minecraft:generic.attack_speed base set 2")
						set {-Speed.Attributesets.%victim's uuid%} to 40

					remove all potions from victim


					

					if {Bliss.GemHealth.%{_uuid}%} >= 4:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 3
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 29
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} is 3:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 5
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 29
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} < 3:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 7
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 29
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true

					set {-SpeedLine.%attacker's uuid%.%victim's uuid%} to true
					wait 3 seconds
					set {-SpeedLine.%attacker's uuid%.%victim's uuid%} to false

			else:

				set {_uuid} to uuid of attacker
				set {_message} to {Speed.Power1.SlothSedative.Display.%{_uuid}%}
				replace all "&b" and "🎯 " with "" in {_message}
				send "<##FEFD17>🔮 <##FD8988>Your &f🎯<##FEFD17>Sloth's Sedative <##FD8988>skill is on cooldown for <##FEFD17>%{_message}%" to attacker



	


every 1 tick:
	loop all players:
		loop all entities:
			if {-SpeedLine.%loop-player-1's uuid%.%loop-entity-2's uuid%} is true:
				set {_v} to vector from loop-player-1's head to loop-entity-2's head
				set vector length of {_v} to 0.1
				set {_loc} to the location 0.7 meters under loop-player-1's head
				loop (distance between {_loc} and loop-entity-2) / 0.1 times:

					draw 1 dust using dustOption(rgb(254, 253, 23), 1) at {_loc} with extra 0 with force for {Bliss.Particles.Default::*}
					draw 1 of smoke at {_loc} with extra 0 with force for {Bliss.Particles.Default::*}
					set {_loc} to {_loc} ~ {_v}	


#every 1 tick:
#	loop all players:
#		loop all entities:
#			if {-SpeedLine.%loop-player-1's uuid%.%loop-entity-2's uuid%} is true:
#				set {_v} to vector from loop-player-1's head to loop-entity-2's head
#				set vector length of {_v} to 0.5
#				set {_loc} to the location 0.7 meters under loop-player-1's head
#				loop (distance between {_loc} and loop-entity-2) / 0.5 times:
#
#					draw 1 dust using dustOption(rgb(254, 253, 23), 1) at {_loc} with force for {Bliss.Particles.Default::*}
#					draw 1 dust_color_transition using dustTransition(black, black, 1) at {_loc} with force for {Bliss.Particles.Default::*}
#					set {_loc} to {_loc} ~ {_v}	


every 1 second:
	loop all offline players:
		if {-Speed.Attributesets.%uuid of loop-offlineplayer%} > 0:
			remove 1 from {-Speed.Attributesets.%uuid of loop-offlineplayer%}
			if {-Speed.Attributesets.%uuid of loop-offlineplayer%} is 0:
				if loop-offlineplayer is online:
					Silentexec("attribute %loop-offlineplayer% minecraft:generic.attack_speed base set 4")
				else:
					set {-Speed.Attributesetsback.%uuid of loop-offlineplayer%} to true

on join:
	set {_uuid} to uuid of player
	if {-Speed.Attributesetsback.%{_uuid}%} is true:
		wait 1 tick
		Silentexec("attribute %player% minecraft:generic.attack_speed base set 4")

	
every 0.25 second:
	loop all players:
		if {-Speed.SpeedStorm.Activated.%uuid of loop-player%} is true:
			set {_num} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.Energy}
			set {_pl} to location of {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}
			set y coord of {_pl} to y coord of {_pl} + 10


			set {_radiusx} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s x coordinate + {_num}  # You can adjust the radius as needed
			set {_radiusz} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s z coordinate + {_num}  # You can adjust the radius as needed

			set {_radiusminusx} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s x coordinate - {_num}
			set {_radiusminusz} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s z coordinate - {_num}

			set {_randomX} to a random number between {_radiusminusx} and {_radiusx}
			set {_randomZ} to a random number between {_radiusminusz} and {_radiusz}

			
			set {_pl}'s x coordinate to {_randomX}
			set {_pl}'s z coordinate to {_randomZ}
			

			loop 30 times:
				set {_pl}'s x coordinate to {_randomX}
				set {_pl}'s z coordinate to {_randomZ}
				set {_pl}'s x coordinate to a random number between {_pl}'s x coordinate - 1 and {_pl}'s x coordinate + 1
				set {_pl}'s z coordinate to a random number between {_pl}'s z coordinate - 1 and {_pl}'s z coordinate + 1
				draw 1 of campfire signal smoke at {_pl} with extra 0 with force


	
every 1 second:
	loop all players:
		if {-Speed.SpeedStorm.Activated.%uuid of loop-player%} is true:
			set {_num} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.Energy}

			set {_radiusx} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s x coordinate + {_num}  # You can adjust the radius as needed
			set {_radiusz} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s z coordinate + {_num}  # You can adjust the radius as needed

			set {_radiusminusx} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s x coordinate - {_num}
			set {_radiusminusz} to {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}'s z coordinate - {_num}

			set {_randomX} to a random number between {_radiusminusx} and {_radiusx}
			set {_randomZ} to a random number between {_radiusminusz} and {_radiusz}

			set {_location} to location of {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}
			
			set {_location}'s x coordinate to {_randomX}
			set {_location}'s z coordinate to {_randomZ}
			

			
																																	

					

			
			strike lightning at {_location}
			set {-Speed.LastStriked} to "%uuid of loop-player%"
			wait 0.4 second
			clear {-Speed.LastStriked}
			

every 1 second:
	loop all players:
		if {-Speed.SpeedStorm.Activated.%uuid of loop-player%} is true:



			if loop-player's off hand item is a amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
				if loop-player doesn't have speed:
					apply speed 1 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 1 without particles to loop-player for 2 seconds replacing the existing effect

			if loop-player's held item is a amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
				if loop-player doesn't have speed:
					apply speed 1 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 1 without particles to loop-player for 2 seconds replacing the existing effect

			if loop-player's off hand item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
				if loop-player doesn't have speed:
					apply speed 2 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 1 without particles to loop-player for 2 seconds replacing the existing effect

			if loop-player's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":
				if loop-player doesn't have speed:
					apply speed 2 without particles to loop-player for 2 seconds replacing the existing effect
				apply dolphins grace 2 without particles to loop-player for 2 seconds replacing the existing effect



			loop all entities within {-Speed.SpeedStorm.Activated.%uuid of loop-player%.Energy} blocks of {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}:
				if loop-entity-2 is not loop-player:
					if loop-entity-2 is a player:
						if "%{Bliss.Trusted.%uuid of loop-player%::*}%" contains "%loop-entity-2's uuid%":
							remove speed from loop-entity-2
							apply speed 3 without particles to loop-player for 1.1 seconds replacing the existing effect
							set {-Speed.Attributesets.%loop-entity-2's uuid%} to {-Speed.Attributesets.%uuid of loop-player%}
							Silentexec("attribute %loop-entity-2% minecraft:generic.attack_speed base set 8.8")
							if loop-entity-2 is not in {_people::*}:
								add loop-entity-2 to {_people::*}

			loop {_people::*}:
				if "%all entities within {-Speed.SpeedStorm.Activated.%uuid of loop-player%.Energy} blocks of {-Speed.SpeedStorm.Activated.%uuid of loop-player%.loc}%" does not contain loop-value-2:
					if "%{Bliss.Trusted.%uuid of loop-player%::*}%" contains "%loop-value-2's uuid%":
						Silentexec("attribute %loop-value-2% minecraft:generic.attack_speed base set 4")

					else:
						Silentexec("attribute %loop-value-2% minecraft:generic.attack_speed base set 4")
						remove loop-value-2 from {_people::*}

				




			

on damage:
	if damage cause is lightning:
		if {-Speed.LastStriked} is set:

			set {_p} to victim
			set {_uuid} to uuid of {_p}
			
			if {-Speed.LastStriked} is "%{_uuid}%":
				set {_no} to true
				set {SpeedStorm.Hitwithstrike.%victim's uuid%} to true
				
				Silentexec("attribute %{_p}% minecraft:generic.attack_speed base set 8.8")
				remove speed from victim
				apply potion of speed of tier 3 without particles to victim for 40 seconds

				
				cancel event
				
			else:
				set {_ps} to {-Speed.LastStriked}
				set {_p} to {_ps} parsed as offline player
				set {_pluuid} to uuid of {_p}
							
				if {-Speed.SpeedStorm.Activated.%{_pluuid}%} is true:
					if "%{Bliss.Trusted.%{_pluuid}%::*}%" contains "%victim's uuid%":

						add victim's uuid to {_allies::*}
						remove victim's uuid from {_enemies::*}
						cancel event

						

						
						#set {-Speed.Attributesets.%victim's uuid%} to 1.2

						#broadcast "Testing %victim% is trusted by %{_p}'s name%"
					
							

				
						
					else:

						add victim's uuid to {_enemies::*}
						remove victim's uuid from {_allies::*}
						if {-Speed.SpeedStorm.Movements.%victim's uuid%} is not set:
							set {-Speed.SpeedStorm.Movements.%victim's uuid%} to 0

						add 2 to {-Speed.SpeedStorm.Movements.%victim's uuid%}
						set {-Speed.SpeedStorm.Movements.%victim's uuid%.TP} to location of victim

						#if victim doesn't have potion effect haste:
							#apply potion of haste of tier 2 to victim for 15 seconds

						#if victim doesn't have potion effect speed:
							#apply potion of speed of tier 3 to victim for 15 seconds
						#broadcast "Testing %victim% isn't trusted by %{_p}'s name%"
							
							

				#else:
					#broadcast "works??????"



on any move:
	if {-Speed.SpeedStorm.Movements.%player's uuid%} > 0:
		cancel event



every 1 second:
	loop all offline players:
		if {-Speed.SpeedStorm.Movements.%loop-offlineplayer's uuid%} > 0:
			remove 1 from {-Speed.SpeedStorm.Movements.%loop-offlineplayer's uuid%}



								
								







			
on right click on entity:
	if distance between player and target entity > 3:
		stop

	if player's held item is amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
		send "<##FEFD17>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if player's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":

			if {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} is not true: 
		


				if lore of player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":	
					set {_num} to 5
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 15
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##57FF8F>Scratched":
					set {_num} to 5
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##7958DB>Cracked":
					set {_num} to 4
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 45
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true
					
				else if lore of player's held item contains "<##FFC929>Damaged":
					set {_num} to 3
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 4
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 00
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##FF1111>Ruined":
					set {_num} to 2
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 5
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true








				send "<##FEFD17>🔮 &f🌩 <##B8FFFB>You have speed and faster crits" to player
				send "<##FEFD17>🔮 <##B8FFFB>You have used group &f🌩<##FEFD17>speed storm <##B8FFFB>skill &7(radius 4)" to player

				loop all players within 4 blocks of target entity:
					if loop-player is not player:
						if "%{Bliss.Trusted.%{_uuid}%::*}%" contains "%loop-player's uuid%":
							send "<##FEFD17>🔮 &f🌩 <##B8FFFB>You have speed and faster crits" to loop-player
							Silentexec("attribute %loop-player% minecraft:generic.attack_speed base set 6")
							set {-Speed.Attributesets.%loop-player's uuid%} to 40
							


				SpeedCircleStorm(1, target entity)	
				SpeedCircleStorm(1.5, target entity)
				SpeedCircleStorm(2, target entity)	
				SpeedCircleStorm(2.5, target entity)	
				SpeedCircleStorm(3, target entity)	
				SpeedCircleStorm(3.5, target entity)	
				SpeedCircleStormLast(4, target entity)

				Silentexec("attribute %player% minecraft:generic.attack_speed base set 6")
				set {-Speed.Attributesets.%player's uuid%} to 40

			else:
				loop {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} times:
					add 60 to {_scoress}

				add {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to {_scoress}
				
				set {_secss} to 0
				set {_minss} to 0
				loop {_scoress} times:
					add 1 to {_secss}
					if {_secss} is 60:
						add 1 to {_minss}
						set {_secss} to 0

				

				if {_secss} is 0:
					if {_minss} > 0:
						set {_ss} to "&b%{_minss}%m"
	

				else if {_minss} > 0:
					set {_ss} to "&b%{_minss}%m %{_secss}%s"					

				else:
					set {_ss} to "&b%{_secss}%s"

				if {_scoress} is 0:
					set {_ss} to "&aReady!"

				replace all "&b" and "🌩 " with "" in {_ss}
				send "<##FEFD17>🔮 <##FD8988>Your &f🌩<##FEFD17>Speedy Storm <##FD8988>skill is on cooldown for <##FEFD17>%{_ss}%" to player
				



on right click:
	if target entity is not set:


	else if distance between player and target entity < 3:
		stop





	
	if player's held item is amethyst shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##C7C7C7>ɢᴇᴍ":
		send "<##FEFD17>🔺 <##FD8988>You need tier 2 gem to cast this skill!" to player

	set {_uuid} to uuid of player
	if {Disabled.%{_uuid}%} < 1:
		if player's held item is a prismarine shard named "<##FEFD17>&lsᴘᴇᴇᴅ &r<##FFD773>ɢᴇᴍ":

			if {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} is not true: 
		


				if lore of player's held item contains "<##57FFC7>Pristine" or "<##57FFC7>Pristine &f+ <##96FFD9>1" or "<##57FFC7>Pristine &f+ <##96FFD9>2" or "<##57FFC7>Pristine &f+ <##96FFD9>3" or "<##57FFC7>Pristine &f+ <##96FFD9>4" or "<##57FFC7>Pristine &f+ <##96FFD9>5":	
					set {_num} to 5
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 15
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##57FF8F>Scratched":
					set {_num} to 5
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##7958DB>Cracked":
					set {_num} to 4
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 1
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 45
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 3
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true
					
				else if lore of player's held item contains "<##FFC929>Damaged":
					set {_num} to 3
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 4
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 00
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

				else if lore of player's held item contains "<##FF1111>Ruined":
					set {_num} to 2
					if player has a dragon egg:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 2
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 30
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true

					else:
						set {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 5
						set {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to 0
						set {-Speed.Power3.SpeedStorm.Cooldown.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to true


						
				set {-Speed.SpeedStorm.Activated.%{_uuid}%} to true
				set {-Speed.SpeedStorm.Activated.%{_uuid}%.Energy} to {_num}
				set {-Speed.SpeedStorm.Activated.%{_uuid}%.loc} to location of player

				Silentexec("attribute %player% minecraft:generic.attack_speed base set 6")

				set {-Speed.Attributesets.%player's uuid%} to 40
				send "<##FEFD17>🔮 <##B8FFFB>You summoned a &f🌩<##FEFD17>speed storm" to player
				set {_s} to 1
				loop {_num} + {_num} times:

					if loop-value is not {_num} + {_num}:
						SpeedStormCircle({_s}, player)
				
						add 0.5 to {_s}

					else:
						SpeedStormCircleLast({_s}, player)

				set {_speedholder} to player
				loop all entities within {_num} blocks of the player:
					if loop-entity is not {_speedholder}:
						if loop-entity is a player:
							if "%{Bliss.Trusted.%{_uuid}%::*}%" contains "%loop-entity's uuid%":
							
								Silentexec("attribute %loop-entity% minecraft:generic.attack_speed base set 5.2")
								set {-Speed.Attributesets.%loop-entity's uuid%} to 40
								
							else:
								send "<##FEFD17>🔮 <##B8FFFB>You have been affected with &f🌩<##FEFD17>speed storm <##B8FFFB>by <##FEFD17>%{_speedholder}%" to loop-entity


				wait 40 seconds
				set {-Speed.SpeedStorm.Activated.%{_uuid}%} to false

			else:

				
				loop {-Speed.Power3.SpeedStorm.Minute.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} times:
					add 60 to {_scoress}

				add {-Speed.Power3.SpeedStorm.Second.%string tag "PublicBukkitValues;blissgems:gem-id" of nbt compound of player's held item%} to {_scoress}
				
				set {_secss} to 0
				set {_minss} to 0
				loop {_scoress} times:
					add 1 to {_secss}
					if {_secss} is 60:
						add 1 to {_minss}
						set {_secss} to 0

				

				if {_secss} is 0:
					if {_minss} > 0:
						set {_ss} to "&b%{_minss}%m"
	

				else if {_minss} > 0:
					set {_ss} to "&b%{_minss}%m %{_secss}%s"					

				else:
					set {_ss} to "&b%{_secss}%s"

				if {_scoress} is 0:
					set {_ss} to "&aReady!"

				replace all "&b" and "🌩 " with "" in {_ss}
				send "<##FEFD17>🔮 <##FD8988>Your &f🌩<##FEFD17>Speedy Storm <##FD8988>skill is on cooldown for <##FEFD17>%{_ss}%" to player

					
	
			
			
		

function SpeedCircleStorm(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_v} to spherical vector with radius {_s}, yaw loop-value and pitch 0
		make 1 of dust using dustOption(rgb(254, 253, 23), 0.9) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
		draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}

function SpeedCircleStormLast(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 10 times:
		loop 360 times:
			set {_v} to spherical vector with radius {_s}, yaw loop-value-2 and pitch 0
			make 1 of dust using dustOption(rgb(254, 253, 23), 0.9) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
			draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*} and {Bliss.Particles.Less::*}
		wait 0.3 seconds

function SpeedCircle(s: number, p: entity):
	SpeedCircleLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 1
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(rgb(254, 253, 23), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}



function SpeedCircleLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value * 3  # Adjust the angle increment
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
		make 1 of dust using dustOption(rgb(254, 253, 23), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
		draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}


function SpeedStormCircle(s: number, p: player):
	SpeedStormCircleLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value-2 * 1.5
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(yellow, 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
		draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}

function SpeedStormCircleLess(s: number, p: player):
	set {_pl} to location of {_p}
	loop 360 times:
		set {_angle} to loop-value-2 * 3
		set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
		make 1 of dust using dustOption(yellow, 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
		draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}


function SpeedCirclelast(s: number, p: entity):
	SpeedCirclelastLess({_s}, {_p})
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 1.5
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
			make 1 of dust using dustOption(rgb(254, 253, 23), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}
		wait 0.3 seconds


function SpeedCirclelastLess(s: number, p: entity):
	set {_pl} to location of {_p}
	loop 7 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 3  # Adjust the angle increment
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0  # Adjust the radius
			make 1 of dust using dustOption(rgb(254, 253, 23), 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Less::*}
			draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Less::*}
		wait 0.3 seconds

function SpeedStormCircleLast(s: number, p: player):
	set {_pl} to location of {_p}
	loop 10 times:
		loop 360 times:
			set {_angle} to loop-value-2 * 1.5
			set {_v} to spherical vector with radius {_s}, yaw {_angle} and pitch 0
			make 1 of dust using dustOption(yellow, 1) at {_pl} ~ {_v} with extra 0 for {Bliss.Particles.Default::*}
			draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force for {Bliss.Particles.Default::*}
		wait 0.4 seconds



